const fs = require('fs');
const path = require('path');

const dir = __dirname;
const topicSkillsPath = path.join(dir, 'topic_skills.json');
const skillDescriptionsPath = path.join(dir, 'skill_descriptions.json');
const skillEdgesPath = path.join(dir, 'skill_edges.json');
const outPath = path.join(dir, 'sync_ontology_to_supabase.sql');

const topicSkills = JSON.parse(fs.readFileSync(topicSkillsPath, 'utf8'));
const skillDescriptions = JSON.parse(fs.readFileSync(skillDescriptionsPath, 'utf8'));
const skillEdges = JSON.parse(fs.readFileSync(skillEdgesPath, 'utf8'));

const topicLabels = {
  EXT: 'External Prerequisites',
  RNUM: 'Real Numbers',
  HCF: 'HCF',
  LCM: 'LCM',
  PCT: 'Percentage',
  SCP: 'Simple and Compound Profit',
  RAP: 'Ratio and Proportions',
  PAL: 'Profit and Loss',
};

const skills = Object.keys(skillDescriptions).sort();

function q(value) {
  if (value === null || value === undefined) {
    return 'NULL';
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

const skillRows = skills.map((skillId) => `  (${q(skillId)}, ${q(skillDescriptions[skillId])})`);

const topicSkillRows = [];
Object.keys(topicSkills)
  .sort()
  .forEach((topicCode) => {
    for (const skillId of topicSkills[topicCode]) {
      topicSkillRows.push(`  (${q(topicCode)}, ${q(skillId)})`);
    }
  });

const topicRows = Object.keys(topicSkills)
  .sort()
  .map((topicCode) => `  (${q(topicCode)}, ${q(topicLabels[topicCode] || topicCode)})`);

const skillEdgeRows = skillEdges
  .map((edge) => `  (${q(edge.source)}, ${q(edge.target)})`)
  .sort();

const sql = `-- Auto-generated from tree_data/topic_skills.json and tree_data/skill_descriptions.json
-- Generated by tree_data/generate_ontology_sync_sql.js
-- Purpose: Keep Supabase skills-related tables consistent with local ontology.

begin;

create table if not exists public.skills (
  skill_id text primary key
);

create temporary table tmp_ontology_skills (
  skill_id text primary key,
  description text not null
) on commit drop;

insert into tmp_ontology_skills (skill_id, description)
values
${skillRows.join(',\n')}
;

create temporary table tmp_ontology_topic_skills (
  topic_code text not null,
  skill_id text not null,
  primary key (topic_code, skill_id)
) on commit drop;

insert into tmp_ontology_topic_skills (topic_code, skill_id)
values
${topicSkillRows.join(',\n')}
;

create temporary table tmp_ontology_topics (
  topic_code text primary key,
  topic_label text not null
) on commit drop;

insert into tmp_ontology_topics (topic_code, topic_label)
values
${topicRows.join(',\n')}
;

create temporary table tmp_ontology_skill_edges (
  source_skill_id text not null,
  target_skill_id text not null,
  primary key (source_skill_id, target_skill_id)
) on commit drop;

insert into tmp_ontology_skill_edges (source_skill_id, target_skill_id)
values
${skillEdgeRows.join(',\n')}
;

-- 1) Ensure every ontology skill exists in public.skills.
--    Dynamically include known description/name columns so NOT NULL constraints are satisfied.
do $$
declare
  cols text := 'skill_id';
  select_expr text := 's.skill_id';
  update_expr text := '';
  col_name text;
begin
  for col_name in
    select column_name
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'skills'
      and column_name in ('skill_description', 'description', 'name', 'skill_name')
    order by case column_name
      when 'skill_description' then 1
      when 'description' then 2
      when 'name' then 3
      when 'skill_name' then 4
      else 99
    end
  loop
    cols := cols || ', ' || quote_ident(col_name);
    select_expr := select_expr || ', s.description';

    if update_expr <> '' then
      update_expr := update_expr || ', ';
    end if;
    update_expr := update_expr || quote_ident(col_name) || ' = excluded.' || quote_ident(col_name);
  end loop;

  if update_expr = '' then
    execute '
      insert into public.skills (skill_id)
      select s.skill_id
      from tmp_ontology_skills s
      on conflict (skill_id) do nothing
    ';
  else
    execute format(
      'insert into public.skills (%s) select %s from tmp_ontology_skills s on conflict (skill_id) do update set %s',
      cols,
      select_expr,
      update_expr
    );
  end if;
end $$;

-- 3) If a topic mapping table exists, sync topic-skill links too.
create table if not exists public.ontology_topics (
  topic_code text primary key,
  topic_label text not null
);

create table if not exists public.ontology_skill_topics (
  topic_code text not null references public.ontology_topics(topic_code) on delete cascade,
  skill_id text not null references public.skills(skill_id) on delete cascade,
  primary key (topic_code, skill_id)
);

create table if not exists public.ontology_skill_edges (
  source_skill_id text not null references public.skills(skill_id) on delete cascade,
  target_skill_id text not null references public.skills(skill_id) on delete cascade,
  primary key (source_skill_id, target_skill_id)
);

insert into public.ontology_topics (topic_code, topic_label)
select topic_code, topic_label
from tmp_ontology_topics
on conflict (topic_code) do update
set topic_label = excluded.topic_label;

delete from public.ontology_skill_topics;
insert into public.ontology_skill_topics (topic_code, skill_id)
select topic_code, skill_id
from tmp_ontology_topic_skills;

delete from public.ontology_skill_edges;
insert into public.ontology_skill_edges (source_skill_id, target_skill_id)
select source_skill_id, target_skill_id
from tmp_ontology_skill_edges;

-- 4) Validation checks.
-- 4a: Missing ontology skills in public.skills (should be zero rows).
select s.skill_id
from tmp_ontology_skills s
left join public.skills t on t.skill_id = s.skill_id
where t.skill_id is null
order by s.skill_id;

-- 4b: Skills in user_skill that are not in public.skills (should be zero rows).
select distinct us.skill_id
from public.user_skill us
left join public.skills s on s.skill_id = us.skill_id
where s.skill_id is null
order by us.skill_id;

-- 4c: Skills in questions that are not in public.skills (should be zero rows).
select distinct q.skill_id
from public.questions q
left join public.skills s on s.skill_id = q.skill_id
where s.skill_id is null
order by q.skill_id;

-- 4d: Row counts for canonical ontology tables.
select count(*) as ontology_topics_count from public.ontology_topics;
select count(*) as ontology_skill_topics_count from public.ontology_skill_topics;
select count(*) as ontology_skill_edges_count from public.ontology_skill_edges;

commit;
`;

fs.writeFileSync(outPath, sql, 'utf8');

console.log('Wrote SQL migration file:');
console.log(outPath);
console.log(`Skills: ${skills.length}`);
console.log(`Topic-skill links: ${topicSkillRows.length}`);
console.log(`Skill-skill edges: ${skillEdgeRows.length}`);
