-- Auto-generated from tree_data/topic_skills.json and tree_data/skill_descriptions.json
-- Generated by tree_data/generate_ontology_sync_sql.js
-- Purpose: Keep Supabase skills-related tables consistent with local ontology.

begin;

create table if not exists public.skills (
  skill_id text primary key
);

create temporary table tmp_ontology_skills (
  skill_id text primary key,
  description text not null
) on commit drop;

insert into tmp_ontology_skills (skill_id, description)
values
  ('AT1', 'Apply Invertendo: if a:b = c:d, then b:a = d:c'),
  ('AT2', 'Apply Alternendo: if a:b = c:d, then a:c = b:d'),
  ('AT3', 'Apply Componendo: if a/b = c/d, then (a+b)/b = (c+d)/d'),
  ('AT4', 'Apply Dividendo: if a/b = c/d, then (a-b)/b = (c-d)/d'),
  ('AT5', 'Apply Componendo-Dividendo: if a/b = c/d, then (a+b)/(a-b) = (c+d)/(c-d)'),
  ('CI1', 'Understand how interest compounds: each period''s profit is added to the principal'),
  ('CI10', 'Find original principal P given A, R, and T under CI'),
  ('CI11', 'Find rate R given P, A, and T under CI (integer T = 2)'),
  ('CI12', 'Find T given P, A, and R under CI by trial or pattern (small integer T)'),
  ('CI13', 'Compute CI for T = 1 and verify it equals SI for the same values'),
  ('CI14', 'Compare CI and SI for same P, R, T and explain the difference'),
  ('CI15', 'Calculate the difference CI − SI = P(R/100)² for T = 2'),
  ('CI16', 'Apply CI to real-world contexts: population growth, depreciation, investment'),
  ('CI17', 'Solve two-step word problems requiring CI computation and comparison'),
  ('CI2', 'Compute CI manually year-by-year for T = 2 and T = 3'),
  ('CI3', 'State the annual compounding formula: A = P(1 + R/100)^T'),
  ('CI4', 'Evaluate (1 + R/100)^T for integer T using repeated multiplication'),
  ('CI5', 'Compute A and CI using A = P(1 + R/100)^T for annual compounding'),
  ('CI6', 'Identify the compounding period (annual, half-yearly, quarterly)'),
  ('CI7', 'Adjust rate and time for half-yearly compounding (R→R/2, T→2T)'),
  ('CI8', 'Adjust rate and time for quarterly compounding (R→R/4, T→4T)'),
  ('CI9', 'Compute A and CI for half-yearly and quarterly compounding periods'),
  ('LG1', 'List multiples of a given number'),
  ('LG10', 'Find HCF of two numbers by factor enumeration (list all factors, pick greatest common)'),
  ('LG11', 'Find HCF of two numbers by common prime factors (prime factorize both, multiply common primes)'),
  ('LG12', 'Find HCF of two numbers by division method (Euclidean algorithm)'),
  ('LG13', 'Find LCM of two numbers by listing and comparing multiples'),
  ('LG14', 'Find LCM of two numbers by prime factorization (take highest power of each prime)'),
  ('LG15', 'Find LCM of two numbers by Euclid''s ladder method (successive division by common/remaining primes)'),
  ('LG16', 'Find HCF of three or more numbers'),
  ('LG17', 'Find LCM of three or more numbers'),
  ('LG18', 'Apply HCF to equal-distribution problems (e.g., divide items into largest equal groups)'),
  ('LG19', 'Apply LCM to scheduling and synchronization problems (e.g., when two periodic events next coincide)'),
  ('LG2', 'Check exact divisibility of one number by another'),
  ('LG20', 'Use the relationship: Product of two numbers = HCF × LCM'),
  ('LG21', 'Find HCF and LCM of fractions: HCF=(HCF of numerators)/(LCM of denominators); LCM=(LCM of numerators)/(HCF of denominators)'),
  ('LG22', 'Find an unknown number given the other number, the HCF, and the LCM, using the product relationship'),
  ('LG23', 'Find HCF and LCM of decimal fractions (equalize decimal places, treat as integers, reposition decimal point)'),
  ('LG3', 'List all factors of a number by trial division'),
  ('LG4', 'Apply divisibility rules for 2, 3, 4, 5, and 9'),
  ('LG5', 'Identify whether a number is prime or composite'),
  ('LG6', 'Find common multiples of two numbers'),
  ('LG7', 'Find common factors of two numbers'),
  ('LG8', 'Express a number as a product of prime factors (factor tree or repeated division)'),
  ('LG9', 'Identify whether two or more numbers are co-prime'),
  ('PC1', 'Define percentage as parts per hundred'),
  ('PC2', 'Express a fraction as a percentage'),
  ('PC3', 'Express a percentage as a fraction'),
  ('PC4', 'Express a decimal as a percentage'),
  ('PC5', 'Express a percentage as a decimal'),
  ('PC6', 'Convert fluently between ratio, fraction, decimal, and percentage'),
  ('PCA1', 'Calculate a percentage of a given quantity'),
  ('PCA2', 'Express one quantity as a percentage of another'),
  ('PCA3', 'Find the original value given a percentage of it'),
  ('PCA4', 'Calculate percentage increase'),
  ('PCA5', 'Calculate percentage decrease'),
  ('PCA6', 'Calculate percentage change (increase or decrease) between two values'),
  ('PF1', 'Define proportion as the equality of two ratios (a:b = c:d)'),
  ('PF2', 'Identify the four terms of a proportion and distinguish means from extremes'),
  ('PF3', 'Apply the cross-multiplication property (product of means = product of extremes)'),
  ('PF4', 'Determine if four numbers are in proportion'),
  ('PF5', 'Find the missing fourth term in a proportion'),
  ('PF6', 'Define and identify continued proportion (a:b = b:c, so b² = ac)'),
  ('PF7', 'Calculate the mean proportional and third proportional in a continued proportion'),
  ('PL1', 'Identify Cost Price (CP) in a word problem, including overhead costs (rent, transport, etc.)'),
  ('PL10', 'Determine the required selling rate (items per taka) to achieve a target profit%'),
  ('PL11', 'Find CP when two different SP scenarios and their difference in value are given'),
  ('PL12', 'Find CP when SP and total amount are both expressed as proportional parts'),
  ('PL13', 'Find original CP through a chain of successive profit percentages (e.g., wholesaler → retailer)'),
  ('PL14', 'Solve VAT problems: find original CP given SP inclusive of VAT, or calculate VAT payable given SP and VAT rate'),
  ('PL15', 'Solve problems where items are bought at two different rates and sold at a uniform rate'),
  ('PL16', 'Find CP and profit% when profit, principal fraction, and time are given together'),
  ('PL17', 'Solve multi-part problems combining percentage, profit/loss, and algebraic equation-setting'),
  ('PL2', 'Identify Selling Price (SP) in a word problem'),
  ('PL3', 'Determine whether a transaction results in profit, loss, or no profit/loss by comparing CP and SP'),
  ('PL4', 'Calculate profit or loss amount (Profit = SP − CP; Loss = CP − SP)'),
  ('PL5', 'Calculate profit or loss percentage on CP'),
  ('PL6', 'Calculate SP given CP and a profit or loss percentage'),
  ('PL7', 'Calculate CP given SP and a profit or loss percentage'),
  ('PL8', 'Calculate CP or SP per unit from a bulk rate'),
  ('PL9', 'Calculate overall profit% or loss% when buying and selling are both expressed in unit-rate form'),
  ('PRE1', 'Identify and write whole numbers up to large values (lakhs/crores)'),
  ('PRE2', 'Add and subtract whole numbers'),
  ('PRE3', 'Multiply whole numbers'),
  ('PRE4', 'Divide whole numbers (including remainders and non-integer results)'),
  ('PRE5', 'Convert between fractions and decimals'),
  ('PRE6', 'Multiply and divide decimal numbers'),
  ('PRE8', 'Basic algebraic manipulation — solve for a single variable'),
  ('PRE9', 'Set up and solve a system of two linear equations with two unknowns'),
  ('RF1', 'Define ratio as a comparison of two quantities of the same kind and unit by division'),
  ('RF10', 'Calculate the compound (mixed) ratio of two or more simple ratios'),
  ('RF11', 'Divide a quantity in a given ratio'),
  ('RF2', 'Identify antecedent and consequent in a ratio'),
  ('RF3', 'Express a ratio as a fraction and vice versa'),
  ('RF4', 'Convert quantities to a common unit before forming a ratio'),
  ('RF5', 'Find equivalent ratios'),
  ('RF6', 'Simplify a ratio to lowest terms using HCF'),
  ('RF7', 'Compare two quantities using ratio'),
  ('RF8', 'Distinguish between ratio of less inequality, greater inequality, and unit ratio'),
  ('RF9', 'Form the inverse ratio by interchanging antecedent and consequent'),
  ('SI1', 'Identify and label the principal (P) in a word problem'),
  ('SI10', 'Solve multi-step word problems combining SI formula with one unknown'),
  ('SI11', 'Calculate SI when rate or time is given as a fraction (e.g., 2.5 years, 7.5%)'),
  ('SI12', 'Calculate SI for part of a year (e.g., 9 months = 9/12 years)'),
  ('SI13', 'Determine the principal required to earn a given SI at given R and T'),
  ('SI14', 'Compare two simple profit schemes and identify the better one'),
  ('SI2', 'Identify and label the rate of profit/interest (R) in a word problem'),
  ('SI3', 'Identify and label the time period (T) in a word problem'),
  ('SI4', 'State the simple profit formula: SI = PRT/100'),
  ('SI5', 'Substitute known values into SI = PRT/100 and compute the result'),
  ('SI6', 'Calculate total amount under simple profit: A = P + SI'),
  ('SI7', 'Isolate P given SI, R, and T (rearrange formula)'),
  ('SI8', 'Isolate R given SI, P, and T (rearrange formula)'),
  ('SI9', 'Isolate T given SI, P, and R (rearrange formula)'),
  ('TP1', 'Define direct proportion'),
  ('TP2', 'Identify if two quantities are in direct proportion'),
  ('TP3', 'Solve problems using direct proportion'),
  ('TP4', 'Define inverse proportion'),
  ('TP5', 'Identify if two quantities are in inverse proportion'),
  ('TP6', 'Solve problems using inverse proportion')
;

create temporary table tmp_ontology_topic_skills (
  topic_code text not null,
  skill_id text not null,
  primary key (topic_code, skill_id)
) on commit drop;

insert into tmp_ontology_topic_skills (topic_code, skill_id)
values
  ('EXT', 'PRE8'),
  ('EXT', 'PRE9'),
  ('HCF', 'LG8'),
  ('HCF', 'LG7'),
  ('HCF', 'LG10'),
  ('HCF', 'LG11'),
  ('HCF', 'LG12'),
  ('HCF', 'LG16'),
  ('HCF', 'LG18'),
  ('HCF', 'LG20'),
  ('HCF', 'LG21'),
  ('LCM', 'LG8'),
  ('LCM', 'LG12'),
  ('LCM', 'LG16'),
  ('LCM', 'LG6'),
  ('LCM', 'LG13'),
  ('LCM', 'LG14'),
  ('LCM', 'LG15'),
  ('LCM', 'LG17'),
  ('LCM', 'LG19'),
  ('LCM', 'LG20'),
  ('LCM', 'LG22'),
  ('LCM', 'LG21'),
  ('LCM', 'LG23'),
  ('PAL', 'PC6'),
  ('PAL', 'PCA1'),
  ('PAL', 'PCA2'),
  ('PAL', 'PCA3'),
  ('PAL', 'SI5'),
  ('PAL', 'PL1'),
  ('PAL', 'PL2'),
  ('PAL', 'PL3'),
  ('PAL', 'PL4'),
  ('PAL', 'PL5'),
  ('PAL', 'PL6'),
  ('PAL', 'PL7'),
  ('PAL', 'PL8'),
  ('PAL', 'PL9'),
  ('PAL', 'PL10'),
  ('PAL', 'PL11'),
  ('PAL', 'PL12'),
  ('PAL', 'PL13'),
  ('PAL', 'PL14'),
  ('PAL', 'PL15'),
  ('PAL', 'PL16'),
  ('PAL', 'PL17'),
  ('PCT', 'PC1'),
  ('PCT', 'PC2'),
  ('PCT', 'PC3'),
  ('PCT', 'PC4'),
  ('PCT', 'PC5'),
  ('PCT', 'PC6'),
  ('PCT', 'PCA1'),
  ('PCT', 'PCA2'),
  ('PCT', 'PCA3'),
  ('PCT', 'PCA4'),
  ('PCT', 'PCA5'),
  ('PCT', 'PCA6'),
  ('PCT', 'PL5'),
  ('PCT', 'PL6'),
  ('PCT', 'PL7'),
  ('RAP', 'LG11'),
  ('RAP', 'RF1'),
  ('RAP', 'RF2'),
  ('RAP', 'RF3'),
  ('RAP', 'RF4'),
  ('RAP', 'RF5'),
  ('RAP', 'RF6'),
  ('RAP', 'RF7'),
  ('RAP', 'RF8'),
  ('RAP', 'RF9'),
  ('RAP', 'RF10'),
  ('RAP', 'RF11'),
  ('RAP', 'PF1'),
  ('RAP', 'PF2'),
  ('RAP', 'PF3'),
  ('RAP', 'PF4'),
  ('RAP', 'PF5'),
  ('RAP', 'PF6'),
  ('RAP', 'PF7'),
  ('RAP', 'TP1'),
  ('RAP', 'TP2'),
  ('RAP', 'TP3'),
  ('RAP', 'TP4'),
  ('RAP', 'TP5'),
  ('RAP', 'TP6'),
  ('RAP', 'AT1'),
  ('RAP', 'AT2'),
  ('RAP', 'AT3'),
  ('RAP', 'AT4'),
  ('RAP', 'AT5'),
  ('RNUM', 'PRE1'),
  ('RNUM', 'PRE2'),
  ('RNUM', 'PRE3'),
  ('RNUM', 'PRE4'),
  ('RNUM', 'PRE5'),
  ('RNUM', 'PRE6'),
  ('RNUM', 'LG2'),
  ('RNUM', 'LG4'),
  ('RNUM', 'LG5'),
  ('RNUM', 'LG9'),
  ('RNUM', 'LG1'),
  ('RNUM', 'LG3'),
  ('RNUM', 'LG8'),
  ('SCP', 'PC1'),
  ('SCP', 'PCA1'),
  ('SCP', 'SI1'),
  ('SCP', 'SI2'),
  ('SCP', 'SI3'),
  ('SCP', 'SI4'),
  ('SCP', 'SI5'),
  ('SCP', 'SI6'),
  ('SCP', 'SI7'),
  ('SCP', 'SI8'),
  ('SCP', 'SI9'),
  ('SCP', 'SI10'),
  ('SCP', 'SI11'),
  ('SCP', 'SI12'),
  ('SCP', 'SI13'),
  ('SCP', 'SI14'),
  ('SCP', 'CI1'),
  ('SCP', 'CI2'),
  ('SCP', 'CI3'),
  ('SCP', 'CI4'),
  ('SCP', 'CI5'),
  ('SCP', 'CI6'),
  ('SCP', 'CI7'),
  ('SCP', 'CI8'),
  ('SCP', 'CI9'),
  ('SCP', 'CI10'),
  ('SCP', 'CI11'),
  ('SCP', 'CI12'),
  ('SCP', 'CI13'),
  ('SCP', 'CI14'),
  ('SCP', 'CI15'),
  ('SCP', 'CI16'),
  ('SCP', 'CI17')
;

create temporary table tmp_ontology_topics (
  topic_code text primary key,
  topic_label text not null
) on commit drop;

insert into tmp_ontology_topics (topic_code, topic_label)
values
  ('EXT', 'External Prerequisites'),
  ('HCF', 'HCF'),
  ('LCM', 'LCM'),
  ('PAL', 'Profit and Loss'),
  ('PCT', 'Percentage'),
  ('RAP', 'Ratio and Proportions'),
  ('RNUM', 'Real Numbers'),
  ('SCP', 'Simple and Compound Profit')
;

create temporary table tmp_ontology_skill_edges (
  source_skill_id text not null,
  target_skill_id text not null,
  primary key (source_skill_id, target_skill_id)
) on commit drop;

insert into tmp_ontology_skill_edges (source_skill_id, target_skill_id)
values
  ('AT3', 'AT5'),
  ('AT4', 'AT5'),
  ('CI1', 'CI2'),
  ('CI1', 'CI3'),
  ('CI1', 'CI6'),
  ('CI13', 'CI14'),
  ('CI14', 'CI15'),
  ('CI14', 'CI17'),
  ('CI3', 'CI4'),
  ('CI4', 'CI5'),
  ('CI5', 'CI10'),
  ('CI5', 'CI11'),
  ('CI5', 'CI12'),
  ('CI5', 'CI13'),
  ('CI5', 'CI9'),
  ('CI6', 'CI7'),
  ('CI6', 'CI8'),
  ('CI7', 'CI9'),
  ('CI8', 'CI9'),
  ('CI9', 'CI16'),
  ('CI9', 'CI17'),
  ('LG1', 'LG6'),
  ('LG10', 'LG16'),
  ('LG11', 'LG16'),
  ('LG11', 'RF6'),
  ('LG12', 'LG15'),
  ('LG12', 'LG16'),
  ('LG13', 'LG17'),
  ('LG14', 'LG17'),
  ('LG15', 'LG17'),
  ('LG16', 'LG18'),
  ('LG16', 'LG20'),
  ('LG16', 'LG21'),
  ('LG17', 'LG19'),
  ('LG17', 'LG20'),
  ('LG17', 'LG21'),
  ('LG2', 'LG12'),
  ('LG2', 'LG4'),
  ('LG2', 'LG5'),
  ('LG20', 'LG22'),
  ('LG21', 'LG23'),
  ('LG3', 'LG5'),
  ('LG3', 'LG7'),
  ('LG3', 'LG8'),
  ('LG5', 'LG8'),
  ('LG5', 'LG9'),
  ('LG6', 'LG13'),
  ('LG7', 'LG10'),
  ('LG7', 'LG11'),
  ('LG8', 'LG11'),
  ('LG8', 'LG14'),
  ('PC1', 'PC2'),
  ('PC1', 'PC3'),
  ('PC1', 'PC4'),
  ('PC1', 'PC5'),
  ('PC1', 'PCA1'),
  ('PC1', 'PCA2'),
  ('PC1', 'SI2'),
  ('PC2', 'PC6'),
  ('PC3', 'PC6'),
  ('PC4', 'PC6'),
  ('PC5', 'PC6'),
  ('PC6', 'PL14'),
  ('PCA1', 'CI2'),
  ('PCA1', 'PCA3'),
  ('PCA1', 'PL6'),
  ('PCA1', 'PL7'),
  ('PCA2', 'PCA4'),
  ('PCA2', 'PCA5'),
  ('PCA2', 'PL5'),
  ('PCA4', 'PCA6'),
  ('PCA5', 'PCA6'),
  ('PF1', 'PF2'),
  ('PF1', 'PF6'),
  ('PF1', 'TP1'),
  ('PF1', 'TP4'),
  ('PF2', 'PF3'),
  ('PF3', 'AT1'),
  ('PF3', 'AT2'),
  ('PF3', 'AT3'),
  ('PF3', 'AT4'),
  ('PF3', 'PF4'),
  ('PF3', 'PF5'),
  ('PF6', 'PF7'),
  ('PL1', 'PL3'),
  ('PL1', 'PL8'),
  ('PL11', 'PL17'),
  ('PL15', 'PL17'),
  ('PL16', 'PL17'),
  ('PL2', 'PL3'),
  ('PL2', 'PL8'),
  ('PL3', 'PL4'),
  ('PL4', 'PL5'),
  ('PL5', 'PL13'),
  ('PL5', 'PL14'),
  ('PL5', 'PL6'),
  ('PL5', 'PL7'),
  ('PL5', 'PL9'),
  ('PL7', 'PL11'),
  ('PL7', 'PL12'),
  ('PL7', 'PL13'),
  ('PL7', 'PL16'),
  ('PL8', 'PL9'),
  ('PL9', 'PL10'),
  ('PL9', 'PL15'),
  ('PRE1', 'PL1'),
  ('PRE1', 'PL2'),
  ('PRE1', 'RF4'),
  ('PRE1', 'SI1'),
  ('PRE1', 'SI3'),
  ('PRE2', 'PL4'),
  ('PRE2', 'SI6'),
  ('PRE3', 'CI4'),
  ('PRE3', 'LG1'),
  ('PRE3', 'PCA1'),
  ('PRE3', 'PF3'),
  ('PRE3', 'PRE5'),
  ('PRE3', 'RF10'),
  ('PRE3', 'RF11'),
  ('PRE3', 'RF5'),
  ('PRE3', 'SI5'),
  ('PRE4', 'LG12'),
  ('PRE4', 'LG2'),
  ('PRE4', 'LG3'),
  ('PRE4', 'PC1'),
  ('PRE4', 'PCA2'),
  ('PRE4', 'PL8'),
  ('PRE4', 'PRE5'),
  ('PRE4', 'RF1'),
  ('PRE5', 'LG21'),
  ('PRE5', 'PC2'),
  ('PRE5', 'PC4'),
  ('PRE5', 'PRE6'),
  ('PRE5', 'RF3'),
  ('PRE5', 'SI11'),
  ('PRE5', 'SI12'),
  ('PRE6', 'LG23'),
  ('PRE8', 'AT1'),
  ('PRE8', 'AT2'),
  ('PRE8', 'AT3'),
  ('PRE8', 'AT4'),
  ('PRE8', 'CI10'),
  ('PRE8', 'CI11'),
  ('PRE8', 'LG22'),
  ('PRE8', 'PCA3'),
  ('PRE8', 'PF5'),
  ('PRE8', 'PF7'),
  ('PRE8', 'PL11'),
  ('PRE8', 'PL16'),
  ('PRE8', 'PL7'),
  ('PRE8', 'SI13'),
  ('PRE8', 'SI7'),
  ('PRE8', 'SI8'),
  ('PRE8', 'SI9'),
  ('PRE8', 'TP3'),
  ('PRE8', 'TP6'),
  ('PRE9', 'PL11'),
  ('PRE9', 'PL17'),
  ('RF1', 'PF1'),
  ('RF1', 'RF10'),
  ('RF1', 'RF2'),
  ('RF1', 'RF3'),
  ('RF1', 'RF5'),
  ('RF1', 'RF6'),
  ('RF2', 'PF2'),
  ('RF2', 'RF9'),
  ('RF3', 'PF6'),
  ('RF3', 'RF7'),
  ('RF6', 'RF11'),
  ('RF7', 'RF8'),
  ('RF7', 'TP2'),
  ('RF7', 'TP5'),
  ('SI1', 'SI4'),
  ('SI2', 'SI4'),
  ('SI3', 'SI4'),
  ('SI4', 'SI5'),
  ('SI5', 'CI13'),
  ('SI5', 'PL16'),
  ('SI5', 'SI11'),
  ('SI5', 'SI12'),
  ('SI5', 'SI14'),
  ('SI5', 'SI6'),
  ('SI5', 'SI7'),
  ('SI5', 'SI8'),
  ('SI5', 'SI9'),
  ('SI6', 'CI1'),
  ('SI6', 'SI10'),
  ('SI7', 'SI10'),
  ('SI7', 'SI13'),
  ('SI8', 'SI10'),
  ('SI9', 'SI10'),
  ('TP1', 'TP2'),
  ('TP2', 'TP3'),
  ('TP4', 'TP5'),
  ('TP5', 'TP6')
;

-- 1) Ensure every ontology skill exists in public.skills.
--    Dynamically include known description/name columns so NOT NULL constraints are satisfied.
do $$
declare
  cols text := 'skill_id';
  select_expr text := 's.skill_id';
  update_expr text := '';
  col_name text;
begin
  for col_name in
    select column_name
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'skills'
      and column_name in ('skill_description', 'description', 'name', 'skill_name')
    order by case column_name
      when 'skill_description' then 1
      when 'description' then 2
      when 'name' then 3
      when 'skill_name' then 4
      else 99
    end
  loop
    cols := cols || ', ' || quote_ident(col_name);
    select_expr := select_expr || ', s.description';

    if update_expr <> '' then
      update_expr := update_expr || ', ';
    end if;
    update_expr := update_expr || quote_ident(col_name) || ' = excluded.' || quote_ident(col_name);
  end loop;

  if update_expr = '' then
    execute '
      insert into public.skills (skill_id)
      select s.skill_id
      from tmp_ontology_skills s
      on conflict (skill_id) do nothing
    ';
  else
    execute format(
      'insert into public.skills (%s) select %s from tmp_ontology_skills s on conflict (skill_id) do update set %s',
      cols,
      select_expr,
      update_expr
    );
  end if;
end $$;

-- 3) If a topic mapping table exists, sync topic-skill links too.
create table if not exists public.ontology_topics (
  topic_code text primary key,
  topic_label text not null
);

create table if not exists public.ontology_skill_topics (
  topic_code text not null references public.ontology_topics(topic_code) on delete cascade,
  skill_id text not null references public.skills(skill_id) on delete cascade,
  primary key (topic_code, skill_id)
);

create table if not exists public.ontology_skill_edges (
  source_skill_id text not null references public.skills(skill_id) on delete cascade,
  target_skill_id text not null references public.skills(skill_id) on delete cascade,
  primary key (source_skill_id, target_skill_id)
);

insert into public.ontology_topics (topic_code, topic_label)
select topic_code, topic_label
from tmp_ontology_topics
on conflict (topic_code) do update
set topic_label = excluded.topic_label;

delete from public.ontology_skill_topics;
insert into public.ontology_skill_topics (topic_code, skill_id)
select topic_code, skill_id
from tmp_ontology_topic_skills;

delete from public.ontology_skill_edges;
insert into public.ontology_skill_edges (source_skill_id, target_skill_id)
select source_skill_id, target_skill_id
from tmp_ontology_skill_edges;

-- 4) Validation checks.
-- 4a: Missing ontology skills in public.skills (should be zero rows).
select s.skill_id
from tmp_ontology_skills s
left join public.skills t on t.skill_id = s.skill_id
where t.skill_id is null
order by s.skill_id;

-- 4b: Skills in user_skill that are not in public.skills (should be zero rows).
select distinct us.skill_id
from public.user_skill us
left join public.skills s on s.skill_id = us.skill_id
where s.skill_id is null
order by us.skill_id;

-- 4c: Skills in questions that are not in public.skills (should be zero rows).
select distinct q.skill_id
from public.questions q
left join public.skills s on s.skill_id = q.skill_id
where s.skill_id is null
order by q.skill_id;

-- 4d: Row counts for canonical ontology tables.
select count(*) as ontology_topics_count from public.ontology_topics;
select count(*) as ontology_skill_topics_count from public.ontology_skill_topics;
select count(*) as ontology_skill_edges_count from public.ontology_skill_edges;

commit;
