import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Nav
    nav: {
      home: 'Home',
      courses: 'Courses',
      about: 'About',
      login: 'Log In',
      signup: 'Sign Up Free',
      logout: 'Log Out',
      hello: 'Hello',
      students: 'Students',
      teachers: 'Teachers',
      institutions: 'Institutions',
      searchPlaceholder: 'What do you want to learn?',
    },
    auth: {
      loginTitle: 'Welcome back to ATLAS',
      loginSubtitle: 'Sign in with your username to continue your adaptive learning journey.',
      loginButton: 'Continue',
      loginButtonLoading: 'Signing in...',
      signupTitle: 'Create your ATLAS account',
      signupHeadline: 'Build your adaptive learning profile',
      signupSubtitle: 'Register with a username and let ATLAS remember your progress, mastery, and course history.',
      signupLabel: 'Sign up',
      signupButton: 'Create account',
      signupButtonLoading: 'Creating account...',
      signupSuccess: 'Account created — redirecting...',
      signupErrorExists: 'This username is already registered. Please log in or choose a different name.',
      signupErrorServer: 'Unable to create your account right now. Please try again later.',
      signupBenefit1Title: 'Quick onboarding',
      signupBenefit1Desc: 'Get a personalized learning path that saves your progress and adapts to your goals.',
      signupBenefit2Title: 'Always in sync',
      signupBenefit2Desc: 'Your practice history and mastery data are saved on the ATLAS server, so you can pick up right where you left off.',
      loginLink: 'Already have an account?',
      signupLink: 'Need an account?',
      loginBadge: 'Username sign-in',
      loginBenefit1Title: 'Pick up where you left off',
      loginBenefit1Desc: 'Your diagnostics, mastery estimates and practice history are saved against your username.',
      loginBenefit2Title: 'One map, any device',
      loginBenefit2Desc: 'Every answer updates your skill estimates on the ATLAS server, so any browser shows the same mastery map.',
      usernameLabel: 'Username',
      usernamePlaceholder: 'Enter your username',
      loginSuccess: 'Login successful — redirecting...',
      loginErrorEmpty: 'Please enter a valid username.',
      loginErrorNotFound: 'No account found with that username.',
      loginErrorServer: 'Unable to connect to the server. Please try again.',
    },
    // Landing
    landing: {
      badge: 'Adaptive learning · Bayesian Knowledge Tracing',
      heroTitleA: 'Learn smarter,',
      heroTitleB: 'not harder.',
      heroSubtitle: 'ATLAS maps what you know, skill by skill, across HSC Physics, Chemistry and Higher Mathematics, finds the prerequisite that is really missing, and asks the question that teaches you most.',
      heroCta: 'Start learning free',
      heroSecondaryCta: 'See how it works',
      heroChipSkills: 'skills',
      heroChipSubjects: 'HSC subjects',
      heroChipBilingual: 'Bangla + English',
      scrollHint: 'Scroll to unfold the map',
      storyEyebrow: 'One map of every skill',
      storyTitle: 'Every dot is a skill you can master.',
      storyIntroA: 'The ATLAS ontology links',
      storyIntroB: 'HSC skills by',
      storyIntroC: 'prerequisite relations, so it can tell which foundation a mistake really comes from.',
      storySkills: 'skills',
      storyPhysicsDesc: 'From measurement and vectors to optics and modern physics.',
      storyChemistryDesc: 'From qualitative analysis and bonding to electrochemistry.',
      storyMathematicsDesc: 'From matrices and vectors to calculus and probability.',
      statsSkills: 'Skills mapped',
      statsEdges: 'Prerequisite links',
      statsSections: 'Sections',
      statsQuestions: 'Verified questions',
      featuresEyebrow: 'What makes it different',
      featuresTitle: 'Built to find the gap, not just the grade.',
      featuresSubtitle: 'Every part of ATLAS is designed around one question: what should you study next?',
      feature1Title: 'Knows what you know',
      feature1Desc: 'Bayesian Knowledge Tracing keeps a mastery estimate for every skill and updates it after every answer, giving higher-order questions more weight than recall.',
      feature2Title: 'Explanations that point at the gap',
      feature2Desc: 'Every option has an explanation, and every wrong option is tagged with the prerequisite it reveals, so a mistake tells you what to study.',
      feature3Title: 'Steps back when you are stuck',
      feature3Desc: 'If three of your last five answers point at the same missing prerequisite, ATLAS gives you two focused questions on it, then returns you to your topic.',
      feature4Title: 'A diagnostic that adapts',
      feature4Desc: 'Each section opens with a short diagnostic. Every question depends on your last answer, and the result sets a starting mastery for every skill in the section.',
      feature5Title: 'Your mastery, as a map',
      feature5Desc: 'Every skill in a section, coloured by how well you know it, with the prerequisite links between them.',
      workflowEyebrow: 'How it works',
      workflowTitle: 'Your learning journey',
      workflowSubtitle: 'Six steps from a first question to mastery',
      step1: 'Pick a section',
      step1Desc: 'Physics, Chemistry or Higher Math',
      step2: 'Take the diagnostic',
      step2Desc: 'Each question adapts to your last answer',
      step3: 'Answer',
      step3Desc: 'Choose one of four options',
      step4: 'Get feedback',
      step4Desc: 'An explanation for the option you chose',
      step5: 'Level up',
      step5Desc: 'Mastery updates across the skill graph',
      step6: 'Master it',
      step6Desc: 'Practise a topic until every skill passes 95%',
      ctaTitle: 'Ready to find your gaps?',
      ctaSubtitle: 'Sign up with a username, take a section diagnostic, and see your mastery map in minutes.',
      ctaButton: 'Get started — it\'s free',
      footerAbout: 'ATLAS is an adaptive tutoring system that models what every student knows, skill by skill, with Bayesian Knowledge Tracing over a prerequisite graph.',
      footerPlatform: 'Platform',
      footerResources: 'Explore',
      footerContact: 'Contact',
      footerHow: 'How it works',
      footerFeatures: 'Features',
      footerProject: 'A CSE 450 capstone project, BUET',
      footerRights: '© 2026 ATLAS. All rights reserved.',
      bilingualEyebrow: 'Bangla + English',
      bilingualTitle: 'Learn in your language.',
      bilingualDesc: 'Switch the whole interface between Bangla and English in one click. Questions are written in Bangla, with mathematics properly typeset.',
      sampleLabel: 'From the question bank',
      sampleHint: 'Pick an answer to see its explanation.',
      sampleCorrect: 'Correct',
      sampleWrong: 'Not quite',
      sampleMissing: 'Tagged missing prerequisite',
      sampleTrace: 'A chemistry mistake, traced to a maths skill.',
      sampleReset: 'Try another option',
      bilingualToggle: 'বাংলায় দেখুন',
      marqueeLabel: 'Sections in the catalogue',
      statsEyebrow: 'Live from the ATLAS database',
      bktCaption: 'Example: the standard BKT update for one Apply-level skill, answer by answer.',
      bktCorrect: 'correct',
      bktWrong: 'wrong',
      spillWrong: '3 of your last 5',
      spillFocus: '2 focused questions',
      spillBack: 'back to your topic',
    },
    // Courses
    courses: {
      welcome: 'Welcome back',
      studentName: 'Student',
      dashboardSubtitle: 'Continue your learning journey',
      activeCourses: 'Active courses',
      activeCoursesCaption: 'with a diagnosed section',
      avgMastery: 'Average mastery',
      avgMasteryCaption: 'across diagnosed sections',
      avgMasteryEmpty: 'Take a diagnostic to start',
      skillsMastered: 'Skills mastered',
      skillsMasteredCaption: 'at 95% or above',
      weeklyTime: 'Study time this week',
      weeklyTimeCaption: 'on this device',
      sectionsDiagnosed: 'sections diagnosed',
      sectionsLabel: 'sections',
      topicsLabel: 'topics',
      hours: 'hours',
      searchCourses: 'Search courses...',
      allSubjects: 'All',
      mathematics: 'Mathematics',
      science: 'Science',
      english: 'English',
      physics: 'Physics',
      chemistry: 'Chemistry',
      continueLearning: 'Continue Learning',
      allCourses: 'All Courses',
      lessons: 'lessons',
      mastery: 'Mastery',
      notStarted: 'Not Started',
      startCourse: 'Start Course',
      continueBtn: 'Continue',
      viewCourse: 'View Course',
      noResults: 'No courses found matching your search.',
    },
    // Lessons
    lessons: {
      backToCourses: 'Back to Courses',
      courseProgress: 'Course Progress',
      overallMastery: 'Overall Mastery',
      totalLessons: 'Total Lessons',
      continueLesson: 'Continue Where You Left Off',
      currentLesson: 'Current Lesson',
      continuePractice: 'Continue Practice',
      completed: 'Completed',
      inProgress: 'In Progress',
      available: 'Available',
      locked: 'Locked',
      startLesson: 'Start Lesson',
      resume: 'Resume',
      questions: 'questions',
      mins: 'min',
    },
    // Practice
    practice: {
      question: 'Question',
      of: 'of',
      mastery: 'Mastery',
      submitAnswer: 'Submit Answer',
      yourAnswer: 'Your answer...',
      getHint: 'Get Hint',
      hints: 'Hints',
      hint: 'Hint',
      locked: 'Locked',
      scaffoldingPrompt: 'Your answer...',
      submitStep: 'Check',
      correct: 'Correct! Great job! 🎉',
      incorrect: 'Not quite right. Try again!',
      backToLesson: 'Back to Lesson',
      nextQuestion: 'Next Question',
      hintPanel: 'Hint Panel',
      tryAnswering: 'Try answering first, then unlock hints if you need help!',
      bktDiagnosis: 'Skill Gap Detected',
      bktSubLesson: 'Mini-Lesson',
      bktRetry: 'Retry',
      bktDiagnosisTitle: 'BKT Analysis: Knowledge Gap Found',
      bktDiagnosisDesc: 'Based on your responses, ATLAS identified a prerequisite skill that needs strengthening.',
      prerequisiteSkill: 'Prerequisite Skill',
      wrongAttempts: 'Wrong',
      startSubLesson: 'Start Mini-Lesson',
      skipToRetry: 'Skip & Retry',
      subLessonDesc: 'Practice these prerequisite questions before retrying.',
      practiceQuestion: 'Practice Question',
      nextPractice: 'Next Practice Question',
      finishSubLesson: 'Finish Mini-Lesson',
      subLessonDone: 'Mini-Lesson Complete!',
      subLessonDoneDesc: "You've strengthened the prerequisite skill. Now let's retry the original question.",
      retryQuestion: 'Retry Original Question',
      retryBanner: 'Great! Now try the question again with your strengthened understanding.',
      finishLesson: 'Finish Lesson',
      lessonComplete: 'Lesson Complete!',
      greatJob: "Great job! You've completed all questions.",
      finalMastery: 'Final Mastery',
      bktTrace: 'BKT Trace',
      bktNoEvents: 'Answer questions to see BKT updates',
    },
  },
  bn: {
    nav: {
      home: 'হোম',
      courses: 'কোর্সসমূহ',
      about: 'আমাদের সম্পর্কে',
      login: 'লগ ইন',
      signup: 'বিনামূল্যে সাইন আপ',
      logout: 'লগ আউট',
      hello: 'হ্যালো',
      students: 'শিক্ষার্থী',
      teachers: 'শিক্ষক',
      institutions: 'প্রতিষ্ঠান',
      searchPlaceholder: 'আপনি কী শিখতে চান?',
    },
    auth: {
      loginTitle: 'আবার স্বাগতম ATLAS-এ',
      loginSubtitle: 'আপনার ব্যক্তিগত শেখার যাত্রা চালিয়ে যাওয়ার জন্য আপনার ব্যবহারকারীর নাম দিয়ে সাইন ইন করুন।',
      loginButton: 'চলুন',
      loginButtonLoading: 'সাইন ইন করা হচ্ছে...',
      signupTitle: 'আপনার ATLAS অ্যাকাউন্ট তৈরি করুন',
      signupHeadline: 'আপনার অভিযোজিত শেখার প্রোফাইল তৈরি করুন',
      signupSubtitle: 'একটি ব্যবহারকারীর নাম দিয়ে নিবন্ধন করুন এবং ATLAS আপনার অগ্রগতি, দক্ষতা এবং কোর্স ইতিহাস মনে রাখবে।',
      signupLabel: 'সাইন আপ',
      signupButton: 'অ্যাকাউন্ট তৈরি করুন',
      signupButtonLoading: 'অ্যাকাউন্ট তৈরি করা হচ্ছে...',
      signupSuccess: 'অ্যাকাউন্ট তৈরি হয়েছে — পুনর্নির্দেশ করা হচ্ছে...',
      signupErrorExists: 'এই ব্যবহারকারীর নাম ইতিমধ্যেই নিবন্ধিত। অনুগ্রহ করে লগ ইন করুন বা একটি ভিন্ন নাম নির্বাচন করুন।',
      signupErrorServer: 'এই মুহূর্তে আপনার অ্যাকাউন্ট তৈরি করা যাচ্ছে না। পরে আবার চেষ্টা করুন।',
      signupBenefit1Title: 'দ্রুত অনবোর্ডিং',
      signupBenefit1Desc: 'একটি ব্যক্তিগত শেখার পথ পান যা আপনার অগ্রগতি সংরক্ষণ করে এবং আপনার লক্ষ্যগুলির সাথে মানিয়ে নেয়।',
      signupBenefit2Title: 'সর্বদা সিঙ্কে',
      signupBenefit2Desc: 'আপনার অনুশীলনের ইতিহাস এবং দক্ষতা ডেটা ATLAS সার্ভারে সংরক্ষিত থাকে যাতে আপনি যেখানে থামলেন সেখানে আবার শুরু করতে পারেন।',
      loginLink: 'ইতোমধ্যে অ্যাকাউন্ট আছে?',
      signupLink: 'অ্যাকাউন্ট নেই?',
      loginBadge: 'ব্যবহারকারীর নাম দিয়ে সাইন ইন',
      loginBenefit1Title: 'যেখানে থেমেছিলেন সেখান থেকে',
      loginBenefit1Desc: 'আপনার ডায়াগনস্টিক, দক্ষতা-অনুমান ও অনুশীলনের ইতিহাস আপনার ব্যবহারকারীর নামে সংরক্ষিত থাকে।',
      loginBenefit2Title: 'যেকোনো ডিভাইসে একই মানচিত্র',
      loginBenefit2Desc: 'প্রতিটি উত্তর ATLAS সার্ভারে আপনার দক্ষতা-অনুমান হালনাগাদ করে, তাই যেকোনো ব্রাউজারে একই দক্ষতার মানচিত্র দেখা যায়।',
      usernameLabel: 'ব্যবহারকারীর নাম',
      usernamePlaceholder: 'আপনার ব্যবহারকারীর নাম লিখুন',
      loginSuccess: 'লগইন সফল — পুনর্নির্দেশ করা হচ্ছে...',
      loginErrorEmpty: 'অনুগ্রহ করে একটি বৈধ ব্যবহারকারীর নাম লিখুন।',
      loginErrorNotFound: 'এই ব্যবহারকারীর নাম সহ কোনো অ্যাকাউন্ট পাওয়া যায়নি।',
      loginErrorServer: 'সার্ভারের সাথে সংযোগ করা যাচ্ছে না। পরে আবার চেষ্টা করুন।',
    },
    landing: {
      badge: 'অভিযোজিত শিক্ষা · বেইসিয়ান নলেজ ট্রেসিং',
      heroTitleA: 'স্মার্টভাবে শিখুন,',
      heroTitleB: 'কঠিনভাবে নয়।',
      heroSubtitle: 'ATLAS এইচএসসি পদার্থবিজ্ঞান, রসায়ন ও উচ্চতর গণিতে আপনি কী জানেন তা প্রতিটি দক্ষতা ধরে মাপে, আসলে কোন পূর্বশর্তটি অনুপস্থিত তা খুঁজে বের করে, আর সেই প্রশ্নটি দেয় যা থেকে আপনি সবচেয়ে বেশি শিখবেন।',
      heroCta: 'বিনামূল্যে শেখা শুরু করুন',
      heroSecondaryCta: 'কিভাবে কাজ করে দেখুন',
      heroChipSkills: 'টি দক্ষতা',
      heroChipSubjects: 'এইচএসসি বিষয়',
      heroChipBilingual: 'বাংলা + ইংরেজি',
      scrollHint: 'স্ক্রল করে মানচিত্রটি খুলুন',
      storyEyebrow: 'সব দক্ষতার একটি মানচিত্র',
      storyTitle: 'প্রতিটি বিন্দু একটি দক্ষতা, যা আপনি আয়ত্ত করতে পারেন।',
      storyIntroA: 'ATLAS অন্টোলজি',
      storyIntroB: 'টি এইচএসসি দক্ষতাকে',
      storyIntroC: 'টি পূর্বশর্ত সম্পর্কে যুক্ত করে, তাই একটি ভুল আসলে কোন ভিত্তি থেকে আসছে তা বুঝতে পারে।',
      storySkills: 'টি দক্ষতা',
      storyPhysicsDesc: 'পরিমাপ ও ভেক্টর থেকে আলোকবিজ্ঞান ও আধুনিক পদার্থবিজ্ঞান পর্যন্ত।',
      storyChemistryDesc: 'গুণগত বিশ্লেষণ ও রাসায়নিক বন্ধন থেকে তড়িৎরসায়ন পর্যন্ত।',
      storyMathematicsDesc: 'ম্যাট্রিক্স ও ভেক্টর থেকে ক্যালকুলাস ও সম্ভাবনা পর্যন্ত।',
      statsSkills: 'চিহ্নিত দক্ষতা',
      statsEdges: 'পূর্বশর্ত সংযোগ',
      statsSections: 'অধ্যায়',
      statsQuestions: 'যাচাইকৃত প্রশ্ন',
      featuresEyebrow: 'কী একে আলাদা করে',
      featuresTitle: 'শুধু নম্বর নয়, ফাঁকটি খুঁজে বের করার জন্য তৈরি।',
      featuresSubtitle: 'ATLAS-এর প্রতিটি অংশ একটি প্রশ্নকে ঘিরে তৈরি: এরপর আপনার কী পড়া উচিত?',
      feature1Title: 'আপনি কী জানেন, তা জানে',
      feature1Desc: 'বেইসিয়ান নলেজ ট্রেসিং প্রতিটি দক্ষতার জন্য একটি দক্ষতা-অনুমান রাখে এবং প্রতিটি উত্তরের পর তা হালনাগাদ করে; উচ্চতর স্তরের প্রশ্নের গুরুত্ব মনে রাখার প্রশ্নের চেয়ে বেশি।',
      feature2Title: 'ব্যাখ্যা, যা ফাঁকটি দেখিয়ে দেয়',
      feature2Desc: 'প্রতিটি অপশনের একটি ব্যাখ্যা আছে, আর প্রতিটি ভুল অপশনে চিহ্নিত আছে কোন পূর্বশর্তের ঘাটতি তা প্রকাশ করে, তাই একটি ভুলই বলে দেয় কী পড়তে হবে।',
      feature3Title: 'আটকে গেলে এক ধাপ পিছিয়ে',
      feature3Desc: 'আপনার শেষ পাঁচটি উত্তরের তিনটি একই অনুপস্থিত পূর্বশর্ত নির্দেশ করলে ATLAS সেটির ওপর দুটি নির্দিষ্ট প্রশ্ন দেয়, তারপর আপনাকে আপনার টপিকে ফিরিয়ে আনে।',
      feature4Title: 'অভিযোজিত ডায়াগনস্টিক',
      feature4Desc: 'প্রতিটি অধ্যায় একটি ছোট ডায়াগনস্টিক দিয়ে শুরু হয়। প্রতিটি প্রশ্ন আপনার আগের উত্তরের ওপর নির্ভর করে, আর ফলাফল অধ্যায়ের প্রতিটি দক্ষতার প্রাথমিক দক্ষতা-মান ঠিক করে।',
      feature5Title: 'আপনার দক্ষতা, একটি মানচিত্রে',
      feature5Desc: 'একটি অধ্যায়ের প্রতিটি দক্ষতা, আপনি কতটা জানেন সেই অনুযায়ী রঙিন, এবং তাদের মধ্যকার পূর্বশর্ত সংযোগসহ।',
      workflowEyebrow: 'কিভাবে কাজ করে',
      workflowTitle: 'আপনার শিক্ষা যাত্রা',
      workflowSubtitle: 'প্রথম প্রশ্ন থেকে দক্ষতা পর্যন্ত ছয়টি ধাপ',
      step1: 'অধ্যায় বাছুন',
      step1Desc: 'পদার্থবিজ্ঞান, রসায়ন বা উচ্চতর গণিত',
      step2: 'ডায়াগনস্টিক দিন',
      step2Desc: 'প্রতিটি প্রশ্ন আপনার আগের উত্তর অনুযায়ী বদলায়',
      step3: 'উত্তর দিন',
      step3Desc: 'চারটি অপশনের একটি বেছে নিন',
      step4: 'ফিডব্যাক পান',
      step4Desc: 'আপনার বেছে নেওয়া অপশনের ব্যাখ্যা',
      step5: 'লেভেল আপ',
      step5Desc: 'দক্ষতা-গ্রাফ জুড়ে আপনার দক্ষতা হালনাগাদ হয়',
      step6: 'আয়ত্ত করুন',
      step6Desc: 'প্রতিটি দক্ষতা ৯৫% পার না হওয়া পর্যন্ত টপিক অনুশীলন করুন',
      ctaTitle: 'আপনার ফাঁকগুলো খুঁজে পেতে প্রস্তুত?',
      ctaSubtitle: 'একটি ব্যবহারকারীর নাম দিয়ে সাইন আপ করুন, একটি অধ্যায়ের ডায়াগনস্টিক দিন, আর কয়েক মিনিটেই আপনার দক্ষতার মানচিত্র দেখুন।',
      ctaButton: 'শুরু করুন — বিনামূল্যে',
      footerAbout: 'ATLAS একটি অভিযোজিত টিউটরিং সিস্টেম, যা পূর্বশর্ত-গ্রাফের ওপর বেইসিয়ান নলেজ ট্রেসিং দিয়ে প্রতিটি শিক্ষার্থী কী জানে তা দক্ষতা ধরে ধরে মডেল করে।',
      footerPlatform: 'প্ল্যাটফর্ম',
      footerResources: 'ঘুরে দেখুন',
      footerContact: 'যোগাযোগ',
      footerHow: 'কিভাবে কাজ করে',
      footerFeatures: 'বৈশিষ্ট্য',
      footerProject: 'CSE 450 ক্যাপস্টোন প্রকল্প, বুয়েট',
      footerRights: '© ২০২৬ ATLAS। সকল স্বত্ব সংরক্ষিত।',
      bilingualEyebrow: 'বাংলা + ইংরেজি',
      bilingualTitle: 'আপনার ভাষায় শিখুন।',
      bilingualDesc: 'এক ক্লিকে পুরো ইন্টারফেস বাংলা ও ইংরেজির মধ্যে বদলান। প্রশ্নগুলো বাংলায় লেখা, আর গাণিতিক রাশি সঠিকভাবে টাইপসেট করা।',
      sampleLabel: 'প্রশ্নব্যাংক থেকে',
      sampleHint: 'ব্যাখ্যা দেখতে একটি উত্তর বেছে নিন।',
      sampleCorrect: 'সঠিক',
      sampleWrong: 'সঠিক নয়',
      sampleMissing: 'চিহ্নিত অনুপস্থিত পূর্বশর্ত',
      sampleTrace: 'রসায়নের একটি ভুল, যার উৎস গণিতের একটি দক্ষতা।',
      sampleReset: 'অন্য অপশন চেষ্টা করুন',
      bilingualToggle: 'Switch to English',
      marqueeLabel: 'ক্যাটালগের অধ্যায়সমূহ',
      statsEyebrow: 'সরাসরি ATLAS ডেটাবেস থেকে',
      bktCaption: 'উদাহরণ: একটি Apply-স্তরের দক্ষতার জন্য প্রতিটি উত্তরের পর আদর্শ BKT হালনাগাদ।',
      bktCorrect: 'সঠিক',
      bktWrong: 'ভুল',
      spillWrong: 'শেষ ৫টির ৩টি',
      spillFocus: '২টি নির্দিষ্ট প্রশ্ন',
      spillBack: 'আবার আপনার টপিকে',
    },
    courses: {
      welcome: 'স্বাগতম',
      studentName: 'শিক্ষার্থী',
      dashboardSubtitle: 'আপনার শিক্ষা যাত্রা চালিয়ে যান',
      activeCourses: 'সক্রিয় কোর্স',
      activeCoursesCaption: 'অন্তত একটি অধ্যায় ডায়াগনোজড',
      avgMastery: 'গড় দক্ষতা',
      avgMasteryCaption: 'ডায়াগনোজড অধ্যায়গুলো জুড়ে',
      avgMasteryEmpty: 'শুরু করতে একটি ডায়াগনস্টিক দিন',
      skillsMastered: 'আয়ত্ত দক্ষতা',
      skillsMasteredCaption: '৯৫% বা তার বেশি',
      weeklyTime: 'এই সপ্তাহের পড়ার সময়',
      weeklyTimeCaption: 'এই ডিভাইসে',
      sectionsDiagnosed: 'অধ্যায় ডায়াগনোজড',
      sectionsLabel: 'অধ্যায়',
      topicsLabel: 'টপিক',
      hours: 'ঘণ্টা',
      searchCourses: 'কোর্স খুঁজুন...',
      allSubjects: 'সব',
      mathematics: 'গণিত',
      science: 'বিজ্ঞান',
      english: 'ইংরেজি',
      physics: 'পদার্থবিজ্ঞান',
      chemistry: 'রসায়ন',
      continueLearning: 'শেখা চালিয়ে যান',
      allCourses: 'সকল কোর্স',
      lessons: 'পাঠ',
      mastery: 'দক্ষতা',
      notStarted: 'শুরু হয়নি',
      startCourse: 'কোর্স শুরু করুন',
      continueBtn: 'চালিয়ে যান',
      viewCourse: 'কোর্স দেখুন',
      noResults: 'আপনার অনুসন্ধানের সাথে মিলে এমন কোনো কোর্স পাওয়া যায়নি।',
    },
    lessons: {
      backToCourses: 'কোর্সে ফিরে যান',
      courseProgress: 'কোর্স অগ্রগতি',
      overallMastery: 'সামগ্রিক দক্ষতা',
      totalLessons: 'মোট পাঠ',
      continueLesson: 'আপনি যেখানে ছেড়েছিলেন সেখান থেকে চালিয়ে যান',
      currentLesson: 'বর্তমান পাঠ',
      continuePractice: 'অনুশীলন চালিয়ে যান',
      completed: 'সম্পন্ন',
      inProgress: 'চলমান',
      available: 'উপলব্ধ',
      locked: 'তালাবদ্ধ',
      startLesson: 'পাঠ শুরু করুন',
      resume: 'পুনরায় শুরু',
      questions: 'প্রশ্ন',
      mins: 'মিনিট',
    },
    practice: {
      question: 'প্রশ্ন',
      of: 'এর মধ্যে',
      mastery: 'দক্ষতা',
      submitAnswer: 'উত্তর জমা দিন',
      yourAnswer: 'আপনার উত্তর...',
      getHint: 'ইঙ্গিত নিন',
      hints: 'ইঙ্গিত',
      hint: 'ইঙ্গিত',
      locked: 'তালাবদ্ধ',
      scaffoldingPrompt: 'আপনার উত্তর...',
      submitStep: 'যাচাই করুন',
      correct: 'সঠিক! চমৎকার! 🎉',
      incorrect: 'সঠিক নয়। আবার চেষ্টা করুন!',
      backToLesson: 'পাঠে ফিরে যান',
      nextQuestion: 'পরবর্তী প্রশ্ন',
      hintPanel: 'ইঙ্গিত প্যানেল',
      tryAnswering: 'প্রথমে উত্তর দেওয়ার চেষ্টা করুন, তারপর প্রয়োজন হলে ইঙ্গিত আনলক করুন!',
      bktDiagnosis: 'দক্ষতার ফাঁক সনাক্ত হয়েছে',
      bktSubLesson: 'মিনি-পাঠ',
      bktRetry: 'পুনরায় চেষ্টা',
      bktDiagnosisTitle: 'BKT বিশ্লেষণ: জ্ঞানের ফাঁক পাওয়া গেছে',
      bktDiagnosisDesc: 'আপনার উত্তরের উপর ভিত্তি করে, ATLAS একটি পূর্বশর্ত দক্ষতা চিহ্নিত করেছে যা শক্তিশালী করতে হবে।',
      prerequisiteSkill: 'পূর্বশর্ত দক্ষতা',
      wrongAttempts: 'ভুল',
      startSubLesson: 'মিনি-পাঠ শুরু করুন',
      skipToRetry: 'এড়িয়ে যান ও পুনরায় চেষ্টা',
      subLessonDesc: 'পুনরায় চেষ্টা করার আগে এই পূর্বশর্ত প্রশ্নগুলি অনুশীলন করুন।',
      practiceQuestion: 'অনুশীলন প্রশ্ন',
      nextPractice: 'পরবর্তী অনুশীলন প্রশ্ন',
      finishSubLesson: 'মিনি-পাঠ শেষ করুন',
      subLessonDone: 'মিনি-পাঠ সম্পন্ন!',
      subLessonDoneDesc: 'আপনি পূর্বশর্ত দক্ষতা শক্তিশালী করেছেন। এখন মূল প্রশ্নে পুনরায় চেষ্টা করুন।',
      retryQuestion: 'মূল প্রশ্নে পুনরায় চেষ্টা',
      retryBanner: 'দারুণ! এখন আপনার শক্তিশালী বোঝাপড়া দিয়ে আবার প্রশ্নটি চেষ্টা করুন।',
      finishLesson: 'পাঠ শেষ করুন',
      lessonComplete: 'পাঠ সম্পন্ন!',
      greatJob: 'চমৎকার! আপনি সব প্রশ্ন সম্পন্ন করেছেন।',
      finalMastery: 'চূড়ান্ত দক্ষতা',
      bktTrace: 'BKT ট্রেস',
      bktNoEvents: 'BKT আপডেট দেখতে প্রশ্নের উত্তর দিন',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('atlas-lang');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('atlas-lang', lang);
    document.documentElement.lang = lang === 'bn' ? 'bn' : 'en';
  }, [lang]);

  const t = (path) => {
    const keys = path.split('.');
    let value = translations[lang];
    for (const key of keys) {
      value = value?.[key];
    }
    return value || path;
  };

  const toggleLang = () => setLang(prev => prev === 'en' ? 'bn' : 'en');

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
