// ─────────────────────────────────────────────
// NODE DATA — HSC Chemistry Skill Ontology (BUET/university admission)
// Layer hierarchy: Subject (Chemistry) → Paper (1st/2nd) → Topic (T1..T14) → Skill node
// ─────────────────────────────────────────────
const SUBJECTS = {
  Chemistry: {
    label: 'Chemistry (HSC)',
    papers: {
      '1st': ["T1", "T2", "T3", "T4", "T5", "T6", "T7"],
      '2nd': ["T8", "T9", "T10", "T11", "T12", "T13", "T14"]
    },
    topics: ["T1", "T2", "T3", "T4", "T5", "T6", "T7", "T8", "T9", "T10", "T11", "T12", "T13", "T14"]
  }
};

const T = {
  T1: { label:'1 · Atomic Structure', paper:'1st', bangla:'পরমাণুর গঠন', subject:'Chemistry', bg:'#D6EAF8', bd:'#2E86C1', fg:'#1A5276' },
  T2: { label:'2 · Periodic Table & Chemical Bonding', paper:'1st', bangla:'পর্যায় সারণি ও রাসায়নিক বন্ধন', subject:'Chemistry', bg:'#D5F5E3', bd:'#1E8449', fg:'#145A32' },
  T3: { label:'3 · Acid, Base & Salt', paper:'1st', bangla:'অম্ল, ক্ষার ও লবণ', subject:'Chemistry', bg:'#FDEBD0', bd:'#CA6F1E', fg:'#784212' },
  T4: { label:'4 · Oxidation–Reduction (Redox)', paper:'1st', bangla:'জারণ-বিজারণ বিক্রিয়া', subject:'Chemistry', bg:'#FADBD8', bd:'#C0392B', fg:'#7B241C' },
  T5: { label:'5 · Behaviour of Gases', paper:'1st', bangla:'গ্যাসের আচরণ', subject:'Chemistry', bg:'#E8DAEF', bd:'#7D3C98', fg:'#4A235A' },
  T6: { label:'6 · Rate of Chemical Change (Kinetics)', paper:'1st', bangla:'রাসায়নিক পরিবর্তনের হার', subject:'Chemistry', bg:'#D1F2EB', bd:'#148F77', fg:'#0E6655' },
  T7: { label:'7 · Thermochemistry', paper:'1st', bangla:'তাপ-রসায়ন', subject:'Chemistry', bg:'#FEF9E7', bd:'#B7950B', fg:'#7D6608' },
  T8: { label:'8 · Environmental Chemistry', paper:'2nd', bangla:'পরিবেশ রসায়ন', subject:'Chemistry', bg:'#D0ECE7', bd:'#16A085', fg:'#0B5345' },
  T9: { label:'9 · Organic Chemistry', paper:'2nd', bangla:'জৈব রসায়ন', subject:'Chemistry', bg:'#FADCEB', bd:'#C2185B', fg:'#7B0B3B' },
  T10: { label:'10 · Electrochemistry', paper:'2nd', bangla:'তড়িৎ-রসায়ন', subject:'Chemistry', bg:'#E3E1FA', bd:'#5B3CC4', fg:'#33206E' },
  T11: { label:'11 · Industrial Chemistry', paper:'2nd', bangla:'শিল্প রসায়ন', subject:'Chemistry', bg:'#EFE0D0', bd:'#935116', fg:'#5A320D' },
  T12: { label:'12 · Biomolecules & Biochemistry', paper:'2nd', bangla:'জৈব রসায়ন (জৈব-অণু/প্রাণরসায়ন)', subject:'Chemistry', bg:'#D6F5FA', bd:'#1B9AAA', fg:'#0E5560' },
  T13: { label:'13 · Nuclear Chemistry', paper:'2nd', bangla:'পারমাণবিক রসায়ন', subject:'Chemistry', bg:'#DCE3EC', bd:'#566573', fg:'#2C3E50' },
  T14: { label:'14 · Applied / Practical Chemistry', paper:'2nd', bangla:'প্রায়োগিক রসায়নের গুরুত্ব', subject:'Chemistry', bg:'#EEF7D6', bd:'#8E9B2C', fg:'#565E1A' },
};

const ND = [
  {id:'CHEM_ATM1', lbl:'ATM1\nDalton\'s\natomic theory', full:'State Dalton\'s atomic theory and its postulates', tp:'T1', sub:'1.1 Early Atomic Theory & Discovery', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM2', lbl:'ATM2\nCathode rays\n& electron', full:'Describe cathode-ray experiments and the discovery of the electron', tp:'T1', sub:'1.1 Early Atomic Theory & Discovery', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM3', lbl:'ATM3\nProton &\nneutron', full:'Describe the discovery of the proton and the neutron', tp:'T1', sub:'1.1 Early Atomic Theory & Discovery', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM4', lbl:'ATM4\nRutherford\'s\nmodel', full:'Explain Rutherford\'s nuclear atomic model and its limitations', tp:'T1', sub:'1.1 Early Atomic Theory & Discovery', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM5', lbl:'ATM5\nBohr\'s\nmodel', full:'Explain Bohr\'s atomic model and its postulates', tp:'T1', sub:'1.2 Bohr Model & Refinements', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM6', lbl:'ATM6\nBohr–Sommerfeld\nmodel', full:'Explain the Bohr–Sommerfeld model as a refinement of Bohr\'s model', tp:'T1', sub:'1.2 Bohr Model & Refinements', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM7', lbl:'ATM7\nOrbitals &\nelectron cloud', full:'Describe atomic orbitals and the electron-cloud concept', tp:'T1', sub:'1.3 Quantum Mechanical Model', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM8', lbl:'ATM8\nQuantum\nnumbers', full:'Identify the four quantum numbers (principal, azimuthal, magnetic, spin) and what each describes', tp:'T1', sub:'1.3 Quantum Mechanical Model', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM9', lbl:'ATM9\nPauli exclusion\nprinciple', full:'State and apply the Pauli exclusion principle', tp:'T1', sub:'1.4 Electron Configuration Rules', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM10', lbl:'ATM10\nAufbau\nprinciple', full:'State and apply the Aufbau principle to fill orbitals in order of energy', tp:'T1', sub:'1.4 Electron Configuration Rules', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM11', lbl:'ATM11\nHund\'s\nrule', full:'State and apply Hund\'s rule of maximum multiplicity', tp:'T1', sub:'1.4 Electron Configuration Rules', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM12', lbl:'ATM12\nElectron\nconfiguration', full:'Write electron configurations of elements using s, p, d, f blocks', tp:'T1', sub:'1.4 Electron Configuration Rules', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM13', lbl:'ATM13\nConfiguration\nexceptions', full:'Explain exceptions to normal electron configuration (Cr, Cu, Mo, Ag, Au)', tp:'T1', sub:'1.4 Electron Configuration Rules', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ATM14', lbl:'ATM14\nIon & excited-\nstate configs', full:'Write electron configurations of ions and atoms in excited states', tp:'T1', sub:'1.4 Electron Configuration Rules', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB1', lbl:'PTB1\nMendeleev\'s\ntable', full:'Describe Mendeleev\'s periodic table and its organizing principle', tp:'T2', sub:'2.1 Development of the Periodic Table', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB2', lbl:'PTB2\nModern\nperiodic table', full:'Describe the modern periodic table in long and short forms', tp:'T2', sub:'2.1 Development of the Periodic Table', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB3', lbl:'PTB3\nPeriods &\ngroups', full:'Describe the characteristic properties of periods and groups', tp:'T2', sub:'2.1 Development of the Periodic Table', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB4', lbl:'PTB4\nAtomic\nradius trend', full:'Explain the trend of atomic radius across periods and down groups', tp:'T2', sub:'2.2 Periodic Trends', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB5', lbl:'PTB5\nIonization\nenergy trend', full:'Explain the trend of ionization energy across periods and down groups', tp:'T2', sub:'2.2 Periodic Trends', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB6', lbl:'PTB6\nElectron\naffinity trend', full:'Explain the trend of electron affinity across periods and down groups', tp:'T2', sub:'2.2 Periodic Trends', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB7', lbl:'PTB7\nElectronegativity\ntrend', full:'Explain the trend of electronegativity across periods and down groups', tp:'T2', sub:'2.2 Periodic Trends', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB8', lbl:'PTB8\nIonic\nbonding', full:'Explain the formation, properties, and conditions for ionic bonding', tp:'T2', sub:'2.3 Ionic & Covalent Bonding', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB9', lbl:'PTB9\nCovalent\nbonding', full:'Explain the formation, properties, and types of covalent bonding', tp:'T2', sub:'2.3 Ionic & Covalent Bonding', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB10', lbl:'PTB10\nCoordinate\ncovalent bond', full:'Explain the formation of coordinate (dative) covalent bonds', tp:'T2', sub:'2.3 Ionic & Covalent Bonding', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB11', lbl:'PTB11\nMetallic\nbonding', full:'Explain metallic bonding using band theory', tp:'T2', sub:'2.3 Ionic & Covalent Bonding', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB12', lbl:'PTB12\nHydrogen\nbonding', full:'Explain intermolecular and intramolecular hydrogen bonding', tp:'T2', sub:'2.4 Molecular Shape & Intermolecular Forces', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB13', lbl:'PTB13\nVSEPR &\nmolecular shape', full:'Predict molecular shapes using VSEPR theory', tp:'T2', sub:'2.4 Molecular Shape & Intermolecular Forces', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB14', lbl:'PTB14\nHybridization', full:'Explain hybridization (sp, sp2, sp3, sp3d, sp3d2) and its effect on molecular geometry', tp:'T2', sub:'2.4 Molecular Shape & Intermolecular Forces', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB15', lbl:'PTB15\nMolecular orbital\ntheory (LCAO)', full:'Explain molecular orbital theory using the LCAO method', tp:'T2', sub:'2.4 Molecular Shape & Intermolecular Forces', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB16', lbl:'PTB16\nDipole moment\n& polarity', full:'Determine dipole moment and molecular polarity', tp:'T2', sub:'2.4 Molecular Shape & Intermolecular Forces', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_PTB17', lbl:'PTB17\nVan der Waals\nforces', full:'Explain weak intermolecular forces (van der Waals forces)', tp:'T2', sub:'2.4 Molecular Shape & Intermolecular Forces', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS1', lbl:'ABS1\nArrhenius\ntheory', full:'State the Arrhenius acid–base theory', tp:'T3', sub:'3.1 Acid–Base Theories', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS2', lbl:'ABS2\nBronsted–Lowry\ntheory', full:'State the Bronsted–Lowry acid–base theory and identify conjugate pairs', tp:'T3', sub:'3.1 Acid–Base Theories', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS3', lbl:'ABS3\nLewis\ntheory', full:'State the Lewis acid–base theory and identify Lewis acids/bases', tp:'T3', sub:'3.1 Acid–Base Theories', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS4', lbl:'ABS4\npH, pOH,\nKa, Kb', full:'Calculate pH, pOH, Ka, and Kb to express acid/base strength', tp:'T3', sub:'3.2 Quantifying Acid–Base Strength', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS5', lbl:'ABS5\nIonic product\nof water (Kw)', full:'Use the ionic product of water (Kw) to relate pH and pOH', tp:'T3', sub:'3.2 Quantifying Acid–Base Strength', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS6', lbl:'ABS6\nIndicators &\npH meters', full:'Use indicators and pH meters to measure solution acidity', tp:'T3', sub:'3.2 Quantifying Acid–Base Strength', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS7', lbl:'ABS7\nBuffer\nsolutions', full:'Explain acidic and basic buffer solutions and how they resist pH change', tp:'T3', sub:'3.3 Buffers', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS8', lbl:'ABS8\nHenderson–\nHasselbalch', full:'Apply the Henderson–Hasselbalch equation to calculate buffer pH', tp:'T3', sub:'3.3 Buffers', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS9', lbl:'ABS9\nSalt\nhydrolysis', full:'Explain salt hydrolysis and predict the pH of salt solutions', tp:'T3', sub:'3.4 Salts & Solubility', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS10', lbl:'ABS10\nSolubility\nproduct (Ksp)', full:'Calculate the solubility product (Ksp) and use it to predict precipitation', tp:'T3', sub:'3.4 Salts & Solubility', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS11', lbl:'ABS11\nCommon ion\neffect', full:'Explain the common ion effect on solubility', tp:'T3', sub:'3.4 Salts & Solubility', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS12', lbl:'ABS12\nSalt\nclassification', full:'Classify salts as normal, acidic, basic, double, or complex', tp:'T3', sub:'3.4 Salts & Solubility', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ABS13', lbl:'ABS13\nSalt\nnomenclature', full:'Apply nomenclature rules to name salts', tp:'T3', sub:'3.4 Salts & Solubility', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX1', lbl:'RDX1\nClassical redox\ndefinitions', full:'State the classical definitions of oxidation and reduction', tp:'T4', sub:'4.1 Concepts of Oxidation–Reduction', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX2', lbl:'RDX2\nElectron-transfer\ndefinition', full:'Define oxidation and reduction in terms of electron transfer', tp:'T4', sub:'4.1 Concepts of Oxidation–Reduction', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX3', lbl:'RDX3\nOxidation\nnumbers', full:'Assign oxidation numbers to atoms in compounds and ions', tp:'T4', sub:'4.1 Concepts of Oxidation–Reduction', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX4', lbl:'RDX4\nIdentify redox\nreactions', full:'Identify redox reactions and the oxidizing/reducing agents involved', tp:'T4', sub:'4.1 Concepts of Oxidation–Reduction', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX5', lbl:'RDX5\nIon-electron\nbalancing', full:'Balance redox equations by the ion-electron method in acidic and basic media', tp:'T4', sub:'4.2 Balancing Redox Equations', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX6', lbl:'RDX6\nOxidation-number\nbalancing', full:'Balance redox equations by the oxidation-number method', tp:'T4', sub:'4.2 Balancing Redox Equations', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX7', lbl:'RDX7\nGalvanic &\nelectrolytic cells', full:'Describe galvanic and electrolytic cells', tp:'T4', sub:'4.3 Electrochemical Cells', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX8', lbl:'RDX8\nElectrode\npotential', full:'Define electrode potential and standard electrode potential', tp:'T4', sub:'4.3 Electrochemical Cells', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX9', lbl:'RDX9\nElectrochemical\nseries', full:'Use the electrochemical series to predict reactivity', tp:'T4', sub:'4.3 Electrochemical Cells', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX10', lbl:'RDX10\nNernst\nequation', full:'Apply the Nernst equation to non-standard electrode potentials', tp:'T4', sub:'4.3 Electrochemical Cells', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX11', lbl:'RDX11\nCell EMF', full:'Calculate cell EMF by combining electrode potentials', tp:'T4', sub:'4.3 Electrochemical Cells', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX12', lbl:'RDX12\nRedox\ntitration', full:'Perform and interpret redox titrations', tp:'T4', sub:'4.4 Applications of Redox Chemistry', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX13', lbl:'RDX13\nCorrosion &\nprevention', full:'Explain corrosion and methods of corrosion prevention', tp:'T4', sub:'4.4 Applications of Redox Chemistry', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_RDX14', lbl:'RDX14\nFaraday\'s laws\n(electrolysis)', full:'Apply Faraday\'s laws of electrolysis to electrolytic processes', tp:'T4', sub:'4.4 Applications of Redox Chemistry', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS1', lbl:'GAS1\nBoyle\'s\nlaw', full:'Apply Boyle\'s law relating pressure and volume at constant temperature', tp:'T5', sub:'5.1 Empirical Gas Laws', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS2', lbl:'GAS2\nCharles\'s\nlaw', full:'Apply Charles\'s law relating volume and temperature at constant pressure', tp:'T5', sub:'5.1 Empirical Gas Laws', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS3', lbl:'GAS3\nGay-Lussac\'s\nlaw', full:'Apply Gay-Lussac\'s law relating pressure and temperature at constant volume', tp:'T5', sub:'5.1 Empirical Gas Laws', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS4', lbl:'GAS4\nAvogadro\'s\nlaw', full:'Apply Avogadro\'s law relating amount of gas and volume', tp:'T5', sub:'5.1 Empirical Gas Laws', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS5', lbl:'GAS5\nIdeal gas\nequation', full:'Apply the ideal gas equation PV = nRT to solve problems', tp:'T5', sub:'5.2 Ideal Gas Equation', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS6', lbl:'GAS6\nMolar volume\nof gas', full:'Calculate the molar volume of an ideal gas', tp:'T5', sub:'5.2 Ideal Gas Equation', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS7', lbl:'GAS7\nKinetic theory\nof gases', full:'State the postulates of the kinetic theory of gases and derive mean kinetic energy', tp:'T5', sub:'5.3 Kinetic Theory', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS8', lbl:'GAS8\nMolecular\nspeeds', full:'Calculate RMS, average, and most-probable speeds of gas molecules', tp:'T5', sub:'5.3 Kinetic Theory', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS9', lbl:'GAS9\nDeviation from\nideal behaviour', full:'Explain deviations of real gases from ideal behaviour', tp:'T5', sub:'5.4 Real Gas Behaviour', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS10', lbl:'GAS10\nVan der Waals\nequation', full:'Apply the van der Waals equation to real gases', tp:'T5', sub:'5.4 Real Gas Behaviour', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS11', lbl:'GAS11\nCritical\nconstants', full:'Define critical temperature, critical pressure, and critical volume', tp:'T5', sub:'5.4 Real Gas Behaviour', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS12', lbl:'GAS12\nLiquefaction\nof gases', full:'Describe liquefaction of gases by the Linde and Claude processes', tp:'T5', sub:'5.4 Real Gas Behaviour', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_GAS13', lbl:'GAS13\nGraham\'s law\nof diffusion', full:'Apply Graham\'s law of diffusion/effusion', tp:'T5', sub:'5.4 Real Gas Behaviour', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN1', lbl:'KIN1\nReaction\nrate defined', full:'Define and express average and instantaneous reaction rate', tp:'T6', sub:'6.1 Rate Fundamentals', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN2', lbl:'KIN2\nRate law\nform & units', full:'Express the rate law mathematically with correct units', tp:'T6', sub:'6.1 Rate Fundamentals', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN3', lbl:'KIN3\nRate law &\nrate constant', full:'Determine the rate law and rate constant from experimental data', tp:'T6', sub:'6.1 Rate Fundamentals', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN4', lbl:'KIN4\nReaction\norder', full:'Determine reaction order (zero, first, second, fractional)', tp:'T6', sub:'6.2 Order & Molecularity', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN5', lbl:'KIN5\nMolecularity\nvs order', full:'Distinguish molecularity from reaction order', tp:'T6', sub:'6.2 Order & Molecularity', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN6', lbl:'KIN6\nIntegrated\nrate equations', full:'Apply integrated rate equations for first- and second-order reactions', tp:'T6', sub:'6.2 Order & Molecularity', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN7', lbl:'KIN7\nHalf-life', full:'Calculate half-life for zero-, first-, and second-order reactions', tp:'T6', sub:'6.2 Order & Molecularity', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN8', lbl:'KIN8\nArrhenius\nequation', full:'Apply the Arrhenius equation to determine activation energy', tp:'T6', sub:'6.3 Activation Energy & Catalysis', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN9', lbl:'KIN9\nCollision\ntheory', full:'Explain activation energy using collision theory', tp:'T6', sub:'6.3 Activation Energy & Catalysis', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN10', lbl:'KIN10\nTransition state\n& activated complex', full:'Describe the transition state and the activated complex', tp:'T6', sub:'6.3 Activation Energy & Catalysis', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN11', lbl:'KIN11\nCatalyst\ntypes', full:'Distinguish homogeneous and heterogeneous catalysis', tp:'T6', sub:'6.3 Activation Energy & Catalysis', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN12', lbl:'KIN12\nCatalytic\nmechanism', full:'Explain catalytic mechanism using energy diagrams and intermediate-compound theory', tp:'T6', sub:'6.3 Activation Energy & Catalysis', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_KIN13', lbl:'KIN13\nFactors\naffecting rate', full:'Explain how concentration, temperature, pressure, and surface area affect reaction rate', tp:'T6', sub:'6.3 Activation Energy & Catalysis', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM1', lbl:'THM1\nSystem,\nsurroundings', full:'Define system, surroundings, and boundary in thermodynamics', tp:'T7', sub:'7.1 Foundations', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM2', lbl:'THM2\nFirst law of\nthermodynamics', full:'State the first law of thermodynamics (conservation of energy)', tp:'T7', sub:'7.1 Foundations', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM3', lbl:'THM3\nInternal energy\n& enthalpy', full:'Define internal energy (ΔU) and enthalpy (ΔH)', tp:'T7', sub:'7.1 Foundations', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM4', lbl:'THM4\nCv and\nCp', full:'Define heat capacity at constant volume (Cv) and constant pressure (Cp)', tp:'T7', sub:'7.1 Foundations', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM5', lbl:'THM5\nTypes of\nenthalpy change', full:'Classify types of enthalpy change', tp:'T7', sub:'7.2 Types of Enthalpy', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM6', lbl:'THM6\nEnthalpy of\nformation', full:'Define and calculate standard enthalpy of formation', tp:'T7', sub:'7.2 Types of Enthalpy', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM7', lbl:'THM7\nEnthalpy of\ncombustion', full:'Define and calculate standard enthalpy of combustion', tp:'T7', sub:'7.2 Types of Enthalpy', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM8', lbl:'THM8\nEnthalpy of\nneutralization', full:'Define and calculate enthalpy of neutralization', tp:'T7', sub:'7.2 Types of Enthalpy', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM9', lbl:'THM9\nEnthalpy of\nsolution', full:'Define and calculate enthalpy of solution', tp:'T7', sub:'7.2 Types of Enthalpy', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM10', lbl:'THM10\nEnthalpy of\nphase change', full:'Define enthalpy of phase transition', tp:'T7', sub:'7.2 Types of Enthalpy', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM11', lbl:'THM11\nHess\'s\nlaw', full:'Apply Hess\'s law to calculate the enthalpy of a reaction indirectly', tp:'T7', sub:'7.3 Hess\'s Law & Bond Energy', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM12', lbl:'THM12\nBond\nenthalpy', full:'Calculate reaction enthalpy from bond dissociation energies', tp:'T7', sub:'7.3 Hess\'s Law & Bond Energy', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM13', lbl:'THM13\nSpontaneity\n& entropy', full:'Explain spontaneity and entropy (ΔS)', tp:'T7', sub:'7.4 Spontaneity & Free Energy', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM14', lbl:'THM14\nGibbs free\nenergy', full:'Calculate Gibbs free energy change (ΔG = ΔH − TΔS)', tp:'T7', sub:'7.4 Spontaneity & Free Energy', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_THM15', lbl:'THM15\nΔG° and\nequilibrium constant', full:'Relate ΔG° to the equilibrium constant (ΔG° = −RT ln K)', tp:'T7', sub:'7.4 Spontaneity & Free Energy', subject:'Chemistry', paper:'1st'},
  {id:'CHEM_ENV1', lbl:'ENV1\nAtmospheric\nlayers', full:'Describe the layers of the atmosphere (troposphere, stratosphere, mesosphere, thermosphere)', tp:'T8', sub:'8.1 Atmosphere & Air Quality', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV2', lbl:'ENV2\nAir\npollutants', full:'Classify primary and secondary air pollutants', tp:'T8', sub:'8.1 Atmosphere & Air Quality', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV3', lbl:'ENV3\nOzone layer\ndepletion', full:'Explain ozone layer depletion and the role of CFCs', tp:'T8', sub:'8.1 Atmosphere & Air Quality', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV4', lbl:'ENV4\nGreenhouse effect\n& warming', full:'Explain the greenhouse effect and global warming caused by greenhouse gases', tp:'T8', sub:'8.1 Atmosphere & Air Quality', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV5', lbl:'ENV5\nAcid\nrain', full:'Explain the formation and effects of acid rain from sulfuric and nitric acids', tp:'T8', sub:'8.1 Atmosphere & Air Quality', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV6', lbl:'ENV6\nPhotochemical\nsmog', full:'Explain the formation of photochemical smog (ozone, PAN, nitrogen oxides)', tp:'T8', sub:'8.1 Atmosphere & Air Quality', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV7', lbl:'ENV7\nWater\nquality', full:'Assess water quality using pH, dissolved oxygen, and hardness', tp:'T8', sub:'8.2 Water Quality & Treatment', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV8', lbl:'ENV8\nWater\npollutants', full:'Classify organic, inorganic, and microbiological water pollutants', tp:'T8', sub:'8.2 Water Quality & Treatment', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV9', lbl:'ENV9\nWastewater\ntreatment', full:'Describe household wastewater treatment processes', tp:'T8', sub:'8.2 Water Quality & Treatment', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV10', lbl:'ENV10\nBOD and\nCOD', full:'Define and calculate biochemical and chemical oxygen demand (BOD, COD)', tp:'T8', sub:'8.2 Water Quality & Treatment', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV11', lbl:'ENV11\nEutrophication', full:'Explain eutrophication and its ecological effects', tp:'T8', sub:'8.2 Water Quality & Treatment', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV12', lbl:'ENV12\nSoil\npollution', full:'Explain soil pollution from pesticides, fertilizers, and heavy metals', tp:'T8', sub:'8.3 Soil & Waste Management', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV13', lbl:'ENV13\nSolid waste\nmanagement', full:'Compare solid waste management methods (recycling, composting, incineration, landfill)', tp:'T8', sub:'8.3 Soil & Waste Management', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ENV14', lbl:'ENV14\nNoise & thermal\npollution', full:'Explain noise pollution and thermal pollution', tp:'T8', sub:'8.3 Soil & Waste Management', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG1', lbl:'ORG1\nCatenation,\nisomerism', full:'Explain catenation, isomerism, and hybridization as foundations of organic chemistry', tp:'T9', sub:'9.1 Foundations & Nomenclature', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG2', lbl:'ORG2\nClassification of\norganic compounds', full:'Classify organic compounds by chain type and functional group', tp:'T9', sub:'9.1 Foundations & Nomenclature', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG3', lbl:'ORG3\nIUPAC\nnomenclature', full:'Apply IUPAC nomenclature to straight-chain, branched, cyclic, and complex compounds', tp:'T9', sub:'9.1 Foundations & Nomenclature', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG4', lbl:'ORG4\nCommon\nnames', full:'Recognize common (trivial) names of organic compounds', tp:'T9', sub:'9.1 Foundations & Nomenclature', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG5', lbl:'ORG5\nAlkanes', full:'Describe alkane properties, preparation, halogenation, combustion, and cracking', tp:'T9', sub:'9.2 Hydrocarbons', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG6', lbl:'ORG6\nAlkenes', full:'Describe alkene preparation and reactions (Markovnikov\'s rule, hydrogenation, halogenation, hydrohalogenation, oxidation, polymerization)', tp:'T9', sub:'9.2 Hydrocarbons', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG7', lbl:'ORG7\nAlkynes', full:'Describe alkyne preparation, acidic nature, and addition reactions', tp:'T9', sub:'9.2 Hydrocarbons', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG8', lbl:'ORG8\nBenzene', full:'Explain benzene\'s structure, stability, and electrophilic substitution (nitration, halogenation, sulfonation, Friedel–Crafts)', tp:'T9', sub:'9.2 Hydrocarbons', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG9', lbl:'ORG9\nDirecting\neffects on benzene', full:'Predict o,p- and m-directing effects of substituents on benzene', tp:'T9', sub:'9.3 Aromatic Directing Effects', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG10', lbl:'ORG10\nAlcohols', full:'Describe alcohol preparation and reactions (esterification, dehydration, oxidation, Lucas reagent)', tp:'T9', sub:'9.4 Oxygen-Containing Compounds', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG11', lbl:'ORG11\nPhenols', full:'Describe phenol preparation, acidic character, and substitution reactions', tp:'T9', sub:'9.4 Oxygen-Containing Compounds', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG12', lbl:'ORG12\nEthers', full:'Describe ether preparation (Williamson synthesis) and reactions', tp:'T9', sub:'9.4 Oxygen-Containing Compounds', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG13', lbl:'ORG13\nAldehydes &\nketones', full:'Describe aldehyde/ketone preparation, Tollens\' and Fehling\'s tests, aldol addition, Cannizzaro reaction', tp:'T9', sub:'9.4 Oxygen-Containing Compounds', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG14', lbl:'ORG14\nCarboxylic\nacids', full:'Describe carboxylic acid preparation, acidic character, esterification, and the haloform reaction', tp:'T9', sub:'9.4 Oxygen-Containing Compounds', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG15', lbl:'ORG15\nAmines', full:'Describe amine preparation, basic character, and diazonium salt formation', tp:'T9', sub:'9.4 Oxygen-Containing Compounds', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG16', lbl:'ORG16\nHalogen\nderivatives', full:'Describe Grignard reagent formation and SN1/SN2 nucleophilic substitution', tp:'T9', sub:'9.5 Halogen Derivatives & Polymers', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG17', lbl:'ORG17\nAddition\npolymers', full:'Describe addition polymers (polyethylene, polypropylene, PVC, Teflon)', tp:'T9', sub:'9.5 Halogen Derivatives & Polymers', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG18', lbl:'ORG18\nCondensation\npolymers', full:'Describe condensation polymers (nylon, terylene, bakelite)', tp:'T9', sub:'9.5 Halogen Derivatives & Polymers', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ORG19', lbl:'ORG19\nNatural\npolymers', full:'Describe natural polymers (cellulose, rubber)', tp:'T9', sub:'9.5 Halogen Derivatives & Polymers', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC1', lbl:'ELC1\nStrong & weak\nelectrolytes', full:'Distinguish strong and weak electrolytes', tp:'T10', sub:'10.1 Electrolytes', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC2', lbl:'ELC2\nDegree of\nionization', full:'Calculate the degree of ionization of an electrolyte', tp:'T10', sub:'10.1 Electrolytes', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC3', lbl:'ELC3\nOstwald\'s dilution\nlaw', full:'Apply Ostwald\'s dilution law', tp:'T10', sub:'10.1 Electrolytes', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC4', lbl:'ELC4\nElectrolytic\ncell', full:'Describe the structure and function of an electrolytic cell', tp:'T10', sub:'10.2 Electrolysis', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC5', lbl:'ELC5\nFaraday\'s laws\nof electrolysis', full:'Apply Faraday\'s first and second laws of electrolysis', tp:'T10', sub:'10.2 Electrolysis', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC6', lbl:'ELC6\nApplications of\nelectrolysis', full:'Describe applications of electrolysis (metal extraction, electroplating, electrorefining)', tp:'T10', sub:'10.2 Electrolysis', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC7', lbl:'ELC7\nSpecific &\nequivalent conductance', full:'Calculate specific and equivalent conductance', tp:'T10', sub:'10.3 Conductance', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC8', lbl:'ELC8\nCell constant', full:'Determine cell constant and measure conductance', tp:'T10', sub:'10.3 Conductance', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC9', lbl:'ELC9\nDaniell\ncell', full:'Describe the Daniell cell as an example of a galvanic cell', tp:'T10', sub:'10.4 Galvanic Cells & Electrode Potential', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC10', lbl:'ELC10\nTypes of\nelectrodes', full:'Classify electrodes as first, second, and inert type', tp:'T10', sub:'10.4 Galvanic Cells & Electrode Potential', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC11', lbl:'ELC11\nStandard hydrogen\nelectrode', full:'Describe the standard hydrogen electrode and reference electrodes', tp:'T10', sub:'10.4 Galvanic Cells & Electrode Potential', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC12', lbl:'ELC12\nStandard electrode\npotential series', full:'Use the standard electrode potential series to compare reactivity', tp:'T10', sub:'10.4 Galvanic Cells & Electrode Potential', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC13', lbl:'ELC13\nNernst equation\napplication', full:'Apply the Nernst equation to determine ion concentration', tp:'T10', sub:'10.4 Galvanic Cells & Electrode Potential', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC14', lbl:'ELC14\nEMF and\nGibbs energy', full:'Relate cell EMF to Gibbs free energy (ΔG = −nFE)', tp:'T10', sub:'10.4 Galvanic Cells & Electrode Potential', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC15', lbl:'ELC15\nBatteries', full:'Compare primary batteries (Leclanché, dry cell) and secondary batteries (lead-acid, lithium-ion)', tp:'T10', sub:'10.5 Batteries, Fuel Cells & Corrosion', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC16', lbl:'ELC16\nFuel\ncells', full:'Describe the hydrogen–oxygen fuel cell', tp:'T10', sub:'10.5 Batteries, Fuel Cells & Corrosion', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_ELC17', lbl:'ELC17\nElectrochemical\ntheory of corrosion', full:'Explain the electrochemical theory of corrosion', tp:'T10', sub:'10.5 Batteries, Fuel Cells & Corrosion', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND1', lbl:'IND1\nFertilizer\nclassification', full:'Classify fertilizers as nitrogenous, phosphatic, or potassic', tp:'T11', sub:'11.1 Fertilizers', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND2', lbl:'IND2\nUrea\nproduction', full:'Describe urea production by the Bosch–Meiser and related processes', tp:'T11', sub:'11.1 Fertilizers', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND3', lbl:'IND3\nAmmonia\nproduction', full:'Describe ammonia production by the Haber–Bosch process', tp:'T11', sub:'11.1 Fertilizers', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND4', lbl:'IND4\nSuperphosphate\nproduction', full:'Describe superphosphate fertilizer production', tp:'T11', sub:'11.1 Fertilizers', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND5', lbl:'IND5\nSulfuric acid\nproduction', full:'Describe sulfuric acid production by the Contact process', tp:'T11', sub:'11.2 Acid Manufacturing', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND6', lbl:'IND6\nNitric acid\nproduction', full:'Describe nitric acid production by the Ostwald process', tp:'T11', sub:'11.2 Acid Manufacturing', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND7', lbl:'IND7\nSodium carbonate\nproduction', full:'Describe sodium carbonate production by the Solvay process', tp:'T11', sub:'11.3 Other Chemical Industries', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND8', lbl:'IND8\nCement\nindustry', full:'Describe cement manufacturing (raw materials, kiln, setting process)', tp:'T11', sub:'11.3 Other Chemical Industries', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND9', lbl:'IND9\nSugar\nindustry', full:'Describe sugar extraction and refining from sugarcane', tp:'T11', sub:'11.3 Other Chemical Industries', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND10', lbl:'IND10\nPaper\nindustry', full:'Describe paper manufacturing (pulping, bleaching, sheet formation)', tp:'T11', sub:'11.3 Other Chemical Industries', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND11', lbl:'IND11\nPetroleum\nrefining', full:'Describe petroleum refining (fractional distillation, cracking, reforming)', tp:'T11', sub:'11.3 Other Chemical Industries', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND12', lbl:'IND12\nPetroleum\nproducts', full:'Identify petroleum products (petrol, diesel, kerosene, lubricating oil, pitch)', tp:'T11', sub:'11.3 Other Chemical Industries', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND13', lbl:'IND13\nSoap &\ndetergent', full:'Describe soap and detergent manufacturing (saponification, detergent types)', tp:'T11', sub:'11.3 Other Chemical Industries', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_IND14', lbl:'IND14\nRayon &\nsynthetic fibers', full:'Describe rayon and synthetic fiber production', tp:'T11', sub:'11.3 Other Chemical Industries', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO1', lbl:'BIO1\nCarbohydrate\nclassification', full:'Classify carbohydrates as monosaccharides, oligosaccharides, and polysaccharides', tp:'T12', sub:'12.1 Carbohydrates', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO2', lbl:'BIO2\nGlucose', full:'Describe glucose structure, open-chain form, anomers, and cyclic structure', tp:'T12', sub:'12.1 Carbohydrates', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO3', lbl:'BIO3\nFructose', full:'Describe fructose structure and properties', tp:'T12', sub:'12.1 Carbohydrates', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO4', lbl:'BIO4\nSucrose', full:'Describe sucrose structure and invert-sugar formation', tp:'T12', sub:'12.1 Carbohydrates', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO5', lbl:'BIO5\nStarch', full:'Describe starch structure (amylose and amylopectin)', tp:'T12', sub:'12.1 Carbohydrates', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO6', lbl:'BIO6\nCellulose', full:'Describe cellulose structure and uses', tp:'T12', sub:'12.1 Carbohydrates', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO7', lbl:'BIO7\nAmino\nacids', full:'Describe natural amino acids, zwitterions, and isoelectric point', tp:'T12', sub:'12.2 Amino Acids & Proteins', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO8', lbl:'BIO8\nPeptide bond &\nprotein structure', full:'Describe peptide bond formation and the levels of protein structure', tp:'T12', sub:'12.2 Amino Acids & Proteins', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO9', lbl:'BIO9\nProtein\nclassification', full:'Classify proteins as simple, conjugated, globular, or fibrous', tp:'T12', sub:'12.2 Amino Acids & Proteins', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO10', lbl:'BIO10\nProtein\ndenaturation', full:'Explain protein denaturation', tp:'T12', sub:'12.2 Amino Acids & Proteins', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO11', lbl:'BIO11\nLipid\nclassification', full:'Classify lipids as simple, complex, or derived', tp:'T12', sub:'12.3 Lipids', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO12', lbl:'BIO12\nFatty\nacids', full:'Distinguish saturated and unsaturated fatty acids', tp:'T12', sub:'12.3 Lipids', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO13', lbl:'BIO13\nSaponification &\niodine number', full:'Calculate saponification number and iodine number of fats/oils', tp:'T12', sub:'12.3 Lipids', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO14', lbl:'BIO14\nNucleic acid\nstructure', full:'Describe DNA and RNA structure (nucleotide, nitrogenous base, sugar, phosphate)', tp:'T12', sub:'12.4 Nucleic Acids', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO15', lbl:'BIO15\nDNA double\nhelix', full:'Describe the DNA double helix and its replication', tp:'T12', sub:'12.4 Nucleic Acids', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO16', lbl:'BIO16\nTypes of\nRNA', full:'Distinguish mRNA, tRNA, and rRNA', tp:'T12', sub:'12.4 Nucleic Acids', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO17', lbl:'BIO17\nEnzymes', full:'Describe enzyme nature, classification, active site, lock-and-key and induced-fit models', tp:'T12', sub:'12.5 Enzymes & Metabolism', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO18', lbl:'BIO18\nFactors affecting\nenzyme activity', full:'Explain the effect of pH, temperature, and substrate concentration on enzyme activity', tp:'T12', sub:'12.5 Enzymes & Metabolism', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_BIO19', lbl:'BIO19\nMetabolism', full:'Describe catabolism (glycolysis, citric acid cycle) and anabolism (photosynthesis, protein synthesis)', tp:'T12', sub:'12.5 Enzymes & Metabolism', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC1', lbl:'NUC1\nNuclear\ncomposition', full:'Describe the composition of the atomic nucleus (protons, neutrons, nucleons)', tp:'T13', sub:'13.1 Nucleus Basics', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC2', lbl:'NUC2\nBinding energy\n& mass defect', full:'Calculate nuclear binding energy and mass defect', tp:'T13', sub:'13.1 Nucleus Basics', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC3', lbl:'NUC3\nIsotopes, isobars,\nisotones, isomers', full:'Distinguish isotopes, isobars, isotones, and isomers', tp:'T13', sub:'13.1 Nucleus Basics', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC4', lbl:'NUC4\nNatural &\nartificial radioactivity', full:'Distinguish natural and artificial radioactivity', tp:'T13', sub:'13.2 Radioactive Decay', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC5', lbl:'NUC5\nAlpha\ndecay', full:'Describe alpha decay and apply the Soddy–Fajans group-displacement law', tp:'T13', sub:'13.2 Radioactive Decay', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC6', lbl:'NUC6\nBeta\ndecay', full:'Describe beta decay (electron and positron emission)', tp:'T13', sub:'13.2 Radioactive Decay', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC7', lbl:'NUC7\nGamma\ndecay', full:'Describe gamma decay as high-energy electromagnetic radiation', tp:'T13', sub:'13.2 Radioactive Decay', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC8', lbl:'NUC8\nRadioactive\ndecay law', full:'Apply the radioactive decay law (N = N0 e^-λt)', tp:'T13', sub:'13.2 Radioactive Decay', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC9', lbl:'NUC9\nHalf-life &\nmean life', full:'Calculate half-life and mean life of radioactive isotopes', tp:'T13', sub:'13.3 Decay Kinetics', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC10', lbl:'NUC10\nRadioactive\nequilibrium', full:'Explain transient and secular radioactive equilibrium', tp:'T13', sub:'13.3 Decay Kinetics', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC11', lbl:'NUC11\nNuclear\nfission', full:'Describe nuclear fission, chain reaction, and critical mass', tp:'T13', sub:'13.4 Nuclear Reactions & Applications', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC12', lbl:'NUC12\nNuclear\nfusion', full:'Describe nuclear fusion as the energy source of the sun and in the hydrogen bomb', tp:'T13', sub:'13.4 Nuclear Reactions & Applications', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC13', lbl:'NUC13\nUses of\nradioisotopes', full:'Describe uses of radioactive isotopes in medicine, agriculture, archaeology (carbon dating), and industry', tp:'T13', sub:'13.4 Nuclear Reactions & Applications', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC14', lbl:'NUC14\nPower plants &\nnuclear weapons', full:'Describe nuclear power plants and nuclear weapons', tp:'T13', sub:'13.4 Nuclear Reactions & Applications', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_NUC15', lbl:'NUC15\nRadioactive\ncontamination', full:'Explain radioactive contamination and safety measures', tp:'T13', sub:'13.4 Nuclear Reactions & Applications', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC1', lbl:'PRC1\nLab safety\nrules', full:'Follow laboratory safety rules and precautions', tp:'T14', sub:'14.1 Laboratory Safety', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC2', lbl:'PRC2\nCation\nidentification', full:'Perform qualitative analysis to identify cations (groups I–VI)', tp:'T14', sub:'14.2 Qualitative Analysis', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC3', lbl:'PRC3\nAnion\nidentification', full:'Perform qualitative analysis to identify anions (carbonate, chloride, sulfate, nitrate, phosphate)', tp:'T14', sub:'14.2 Qualitative Analysis', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC4', lbl:'PRC4\nAcid–base\ntitration', full:'Perform quantitative volumetric analysis by acid–base titration', tp:'T14', sub:'14.3 Quantitative Analysis', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC5', lbl:'PRC5\nRedox\ntitration methods', full:'Perform quantitative redox titration (permanganometry and iodometry)', tp:'T14', sub:'14.3 Quantitative Analysis', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC6', lbl:'PRC6\nGravimetric\nanalysis', full:'Perform quantitative gravimetric analysis (precipitation and heating methods)', tp:'T14', sub:'14.3 Quantitative Analysis', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC7', lbl:'PRC7\nCommon salt\npreparation', full:'Prepare common salts (NaCl, Na2CO3, CuSO4·5H2O, Mohr\'s salt)', tp:'T14', sub:'14.4 Preparations & Standard Solutions', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC8', lbl:'PRC8\nStandard solution\npreparation', full:'Prepare primary and secondary standard solutions', tp:'T14', sub:'14.4 Preparations & Standard Solutions', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC9', lbl:'PRC9\nIndicator types\n& use', full:'Select and use indicators (methyl orange, phenolphthalein, starch) appropriately', tp:'T14', sub:'14.4 Preparations & Standard Solutions', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC10', lbl:'PRC10\nElectrolysis\nexperiments', full:'Carry out electrolysis experiments (electrolysis of water, CuSO4 solution)', tp:'T14', sub:'14.5 Experimental Techniques', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC11', lbl:'PRC11\nThermal\nanalysis', full:'Perform thermal analysis by observing changes in a solid on heating', tp:'T14', sub:'14.5 Experimental Techniques', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC12', lbl:'PRC12\nCrystallization', full:'Explain crystal formation and crystallization techniques', tp:'T14', sub:'14.5 Experimental Techniques', subject:'Chemistry', paper:'2nd'},
  {id:'CHEM_PRC13', lbl:'PRC13\nLab report &\nerror analysis', full:'Write laboratory reports following proper conventions and analyze experimental error', tp:'T14', sub:'14.5 Experimental Techniques', subject:'Chemistry', paper:'2nd'},
];

const ED = [
  ['CHEM_ATM1','CHEM_ATM2'],
  ['CHEM_ATM2','CHEM_ATM3'],
  ['CHEM_ATM3','CHEM_ATM4'],
  ['CHEM_ATM5','CHEM_ATM6'],
  ['CHEM_ATM7','CHEM_ATM8'],
  ['CHEM_ATM9','CHEM_ATM10'],
  ['CHEM_ATM10','CHEM_ATM11'],
  ['CHEM_ATM11','CHEM_ATM12'],
  ['CHEM_ATM12','CHEM_ATM13'],
  ['CHEM_ATM13','CHEM_ATM14'],
  ['CHEM_ATM4','CHEM_ATM5'],
  ['CHEM_ATM6','CHEM_ATM7'],
  ['CHEM_ATM8','CHEM_ATM9'],
  ['CHEM_PTB1','CHEM_PTB2'],
  ['CHEM_PTB2','CHEM_PTB3'],
  ['CHEM_PTB4','CHEM_PTB5'],
  ['CHEM_PTB5','CHEM_PTB6'],
  ['CHEM_PTB6','CHEM_PTB7'],
  ['CHEM_PTB8','CHEM_PTB9'],
  ['CHEM_PTB9','CHEM_PTB10'],
  ['CHEM_PTB10','CHEM_PTB11'],
  ['CHEM_PTB12','CHEM_PTB13'],
  ['CHEM_PTB13','CHEM_PTB14'],
  ['CHEM_PTB14','CHEM_PTB15'],
  ['CHEM_PTB15','CHEM_PTB16'],
  ['CHEM_PTB16','CHEM_PTB17'],
  ['CHEM_PTB3','CHEM_PTB4'],
  ['CHEM_PTB7','CHEM_PTB8'],
  ['CHEM_PTB11','CHEM_PTB12'],
  ['CHEM_ABS1','CHEM_ABS2'],
  ['CHEM_ABS2','CHEM_ABS3'],
  ['CHEM_ABS4','CHEM_ABS5'],
  ['CHEM_ABS5','CHEM_ABS6'],
  ['CHEM_ABS7','CHEM_ABS8'],
  ['CHEM_ABS9','CHEM_ABS10'],
  ['CHEM_ABS10','CHEM_ABS11'],
  ['CHEM_ABS11','CHEM_ABS12'],
  ['CHEM_ABS12','CHEM_ABS13'],
  ['CHEM_ABS3','CHEM_ABS4'],
  ['CHEM_ABS6','CHEM_ABS7'],
  ['CHEM_ABS8','CHEM_ABS9'],
  ['CHEM_RDX1','CHEM_RDX2'],
  ['CHEM_RDX2','CHEM_RDX3'],
  ['CHEM_RDX3','CHEM_RDX4'],
  ['CHEM_RDX5','CHEM_RDX6'],
  ['CHEM_RDX7','CHEM_RDX8'],
  ['CHEM_RDX8','CHEM_RDX9'],
  ['CHEM_RDX9','CHEM_RDX10'],
  ['CHEM_RDX10','CHEM_RDX11'],
  ['CHEM_RDX12','CHEM_RDX13'],
  ['CHEM_RDX13','CHEM_RDX14'],
  ['CHEM_RDX4','CHEM_RDX5'],
  ['CHEM_RDX6','CHEM_RDX7'],
  ['CHEM_RDX11','CHEM_RDX12'],
  ['CHEM_GAS1','CHEM_GAS2'],
  ['CHEM_GAS2','CHEM_GAS3'],
  ['CHEM_GAS3','CHEM_GAS4'],
  ['CHEM_GAS5','CHEM_GAS6'],
  ['CHEM_GAS7','CHEM_GAS8'],
  ['CHEM_GAS9','CHEM_GAS10'],
  ['CHEM_GAS10','CHEM_GAS11'],
  ['CHEM_GAS11','CHEM_GAS12'],
  ['CHEM_GAS12','CHEM_GAS13'],
  ['CHEM_GAS4','CHEM_GAS5'],
  ['CHEM_GAS6','CHEM_GAS7'],
  ['CHEM_GAS8','CHEM_GAS9'],
  ['CHEM_KIN1','CHEM_KIN2'],
  ['CHEM_KIN2','CHEM_KIN3'],
  ['CHEM_KIN4','CHEM_KIN5'],
  ['CHEM_KIN5','CHEM_KIN6'],
  ['CHEM_KIN6','CHEM_KIN7'],
  ['CHEM_KIN8','CHEM_KIN9'],
  ['CHEM_KIN9','CHEM_KIN10'],
  ['CHEM_KIN10','CHEM_KIN11'],
  ['CHEM_KIN11','CHEM_KIN12'],
  ['CHEM_KIN12','CHEM_KIN13'],
  ['CHEM_KIN3','CHEM_KIN4'],
  ['CHEM_KIN7','CHEM_KIN8'],
  ['CHEM_THM1','CHEM_THM2'],
  ['CHEM_THM2','CHEM_THM3'],
  ['CHEM_THM3','CHEM_THM4'],
  ['CHEM_THM5','CHEM_THM6'],
  ['CHEM_THM6','CHEM_THM7'],
  ['CHEM_THM7','CHEM_THM8'],
  ['CHEM_THM8','CHEM_THM9'],
  ['CHEM_THM9','CHEM_THM10'],
  ['CHEM_THM11','CHEM_THM12'],
  ['CHEM_THM13','CHEM_THM14'],
  ['CHEM_THM14','CHEM_THM15'],
  ['CHEM_THM4','CHEM_THM5'],
  ['CHEM_THM10','CHEM_THM11'],
  ['CHEM_THM12','CHEM_THM13'],
  ['CHEM_ENV1','CHEM_ENV2'],
  ['CHEM_ENV2','CHEM_ENV3'],
  ['CHEM_ENV3','CHEM_ENV4'],
  ['CHEM_ENV4','CHEM_ENV5'],
  ['CHEM_ENV5','CHEM_ENV6'],
  ['CHEM_ENV7','CHEM_ENV8'],
  ['CHEM_ENV8','CHEM_ENV9'],
  ['CHEM_ENV9','CHEM_ENV10'],
  ['CHEM_ENV10','CHEM_ENV11'],
  ['CHEM_ENV12','CHEM_ENV13'],
  ['CHEM_ENV13','CHEM_ENV14'],
  ['CHEM_ENV6','CHEM_ENV7'],
  ['CHEM_ENV11','CHEM_ENV12'],
  ['CHEM_ORG1','CHEM_ORG2'],
  ['CHEM_ORG2','CHEM_ORG3'],
  ['CHEM_ORG3','CHEM_ORG4'],
  ['CHEM_ORG5','CHEM_ORG6'],
  ['CHEM_ORG6','CHEM_ORG7'],
  ['CHEM_ORG7','CHEM_ORG8'],
  ['CHEM_ORG10','CHEM_ORG11'],
  ['CHEM_ORG11','CHEM_ORG12'],
  ['CHEM_ORG12','CHEM_ORG13'],
  ['CHEM_ORG13','CHEM_ORG14'],
  ['CHEM_ORG14','CHEM_ORG15'],
  ['CHEM_ORG16','CHEM_ORG17'],
  ['CHEM_ORG17','CHEM_ORG18'],
  ['CHEM_ORG18','CHEM_ORG19'],
  ['CHEM_ORG4','CHEM_ORG5'],
  ['CHEM_ORG8','CHEM_ORG9'],
  ['CHEM_ORG9','CHEM_ORG10'],
  ['CHEM_ORG15','CHEM_ORG16'],
  ['CHEM_ELC1','CHEM_ELC2'],
  ['CHEM_ELC2','CHEM_ELC3'],
  ['CHEM_ELC4','CHEM_ELC5'],
  ['CHEM_ELC5','CHEM_ELC6'],
  ['CHEM_ELC7','CHEM_ELC8'],
  ['CHEM_ELC9','CHEM_ELC10'],
  ['CHEM_ELC10','CHEM_ELC11'],
  ['CHEM_ELC11','CHEM_ELC12'],
  ['CHEM_ELC12','CHEM_ELC13'],
  ['CHEM_ELC13','CHEM_ELC14'],
  ['CHEM_ELC15','CHEM_ELC16'],
  ['CHEM_ELC16','CHEM_ELC17'],
  ['CHEM_ELC3','CHEM_ELC4'],
  ['CHEM_ELC6','CHEM_ELC7'],
  ['CHEM_ELC8','CHEM_ELC9'],
  ['CHEM_ELC14','CHEM_ELC15'],
  ['CHEM_IND1','CHEM_IND2'],
  ['CHEM_IND2','CHEM_IND3'],
  ['CHEM_IND3','CHEM_IND4'],
  ['CHEM_IND5','CHEM_IND6'],
  ['CHEM_IND7','CHEM_IND8'],
  ['CHEM_IND8','CHEM_IND9'],
  ['CHEM_IND9','CHEM_IND10'],
  ['CHEM_IND10','CHEM_IND11'],
  ['CHEM_IND11','CHEM_IND12'],
  ['CHEM_IND12','CHEM_IND13'],
  ['CHEM_IND13','CHEM_IND14'],
  ['CHEM_IND4','CHEM_IND5'],
  ['CHEM_IND6','CHEM_IND7'],
  ['CHEM_BIO1','CHEM_BIO2'],
  ['CHEM_BIO2','CHEM_BIO3'],
  ['CHEM_BIO3','CHEM_BIO4'],
  ['CHEM_BIO4','CHEM_BIO5'],
  ['CHEM_BIO5','CHEM_BIO6'],
  ['CHEM_BIO7','CHEM_BIO8'],
  ['CHEM_BIO8','CHEM_BIO9'],
  ['CHEM_BIO9','CHEM_BIO10'],
  ['CHEM_BIO11','CHEM_BIO12'],
  ['CHEM_BIO12','CHEM_BIO13'],
  ['CHEM_BIO14','CHEM_BIO15'],
  ['CHEM_BIO15','CHEM_BIO16'],
  ['CHEM_BIO17','CHEM_BIO18'],
  ['CHEM_BIO18','CHEM_BIO19'],
  ['CHEM_BIO6','CHEM_BIO7'],
  ['CHEM_BIO10','CHEM_BIO11'],
  ['CHEM_BIO13','CHEM_BIO14'],
  ['CHEM_BIO16','CHEM_BIO17'],
  ['CHEM_NUC1','CHEM_NUC2'],
  ['CHEM_NUC2','CHEM_NUC3'],
  ['CHEM_NUC4','CHEM_NUC5'],
  ['CHEM_NUC5','CHEM_NUC6'],
  ['CHEM_NUC6','CHEM_NUC7'],
  ['CHEM_NUC7','CHEM_NUC8'],
  ['CHEM_NUC9','CHEM_NUC10'],
  ['CHEM_NUC11','CHEM_NUC12'],
  ['CHEM_NUC12','CHEM_NUC13'],
  ['CHEM_NUC13','CHEM_NUC14'],
  ['CHEM_NUC14','CHEM_NUC15'],
  ['CHEM_NUC3','CHEM_NUC4'],
  ['CHEM_NUC8','CHEM_NUC9'],
  ['CHEM_NUC10','CHEM_NUC11'],
  ['CHEM_PRC2','CHEM_PRC3'],
  ['CHEM_PRC4','CHEM_PRC5'],
  ['CHEM_PRC5','CHEM_PRC6'],
  ['CHEM_PRC7','CHEM_PRC8'],
  ['CHEM_PRC8','CHEM_PRC9'],
  ['CHEM_PRC10','CHEM_PRC11'],
  ['CHEM_PRC11','CHEM_PRC12'],
  ['CHEM_PRC12','CHEM_PRC13'],
  ['CHEM_PRC1','CHEM_PRC2'],
  ['CHEM_PRC3','CHEM_PRC4'],
  ['CHEM_PRC6','CHEM_PRC7'],
  ['CHEM_PRC9','CHEM_PRC10'],
  ['CHEM_ATM14','CHEM_PTB1'],
  ['CHEM_PTB17','CHEM_ABS1'],
  ['CHEM_ABS13','CHEM_RDX1'],
  ['CHEM_RDX14','CHEM_GAS1'],
  ['CHEM_GAS13','CHEM_KIN1'],
  ['CHEM_KIN13','CHEM_THM1'],
  ['CHEM_THM15','CHEM_ENV1'],
  ['CHEM_ENV14','CHEM_ORG1'],
  ['CHEM_ORG19','CHEM_ELC1'],
  ['CHEM_ELC17','CHEM_IND1'],
  ['CHEM_IND14','CHEM_BIO1'],
  ['CHEM_BIO19','CHEM_NUC1'],
  ['CHEM_NUC15','CHEM_PRC1'],
  ['CHEM_ATM12','CHEM_PTB8'],
  ['CHEM_ATM12','CHEM_PTB9'],
  ['CHEM_PTB9','CHEM_ABS1'],
  ['CHEM_PTB7','CHEM_RDX3'],
  ['CHEM_ABS4','CHEM_RDX12'],
  ['CHEM_ATM1','CHEM_GAS7'],
  ['CHEM_GAS7','CHEM_KIN9'],
  ['CHEM_KIN8','CHEM_THM2'],
  ['CHEM_PTB9','CHEM_ENV3'],
  ['CHEM_ABS4','CHEM_ENV5'],
  ['CHEM_PTB14','CHEM_ORG1'],
  ['CHEM_PTB9','CHEM_ORG2'],
  ['CHEM_RDX8','CHEM_ELC9'],
  ['CHEM_RDX9','CHEM_ELC12'],
  ['CHEM_RDX10','CHEM_ELC13'],
  ['CHEM_RDX14','CHEM_ELC5'],
  ['CHEM_RDX7','CHEM_ELC4'],
  ['CHEM_ABS1','CHEM_IND5'],
  ['CHEM_ELC6','CHEM_IND1'],
  ['CHEM_ORG13','CHEM_BIO2'],
  ['CHEM_ORG14','CHEM_BIO12'],
  ['CHEM_ORG15','CHEM_BIO7'],
  ['CHEM_ATM3','CHEM_NUC1'],
  ['CHEM_ABS6','CHEM_PRC9'],
  ['CHEM_RDX12','CHEM_PRC5'],
  ['CHEM_ELC4','CHEM_PRC10'],
  ['CHEM_ABS10','CHEM_PRC6'],
];


const nodeMap = {};
ND.forEach(n => { nodeMap[n.id] = n; });

// Build adjacency: incoming edges
const inEdges = {}; // skillId → [prerequisite skillIds]
ED.forEach(([src, tgt]) => {
  if (!inEdges[tgt]) inEdges[tgt] = [];
  inEdges[tgt].push(src);
});

// Get all ancestors (direct prerequisites first, then transitive)
function getPrerequisites(skillId, depth = 0, visited = new Set()) {
  if (visited.has(skillId) || depth > 10) return [];
  visited.add(skillId);
  const directPrereqs = inEdges[skillId] || [];
  const result = directPrereqs.map(prereqId => ({
    id: prereqId,
    full: nodeMap[prereqId]?.full || prereqId,
    depth
  }));
  directPrereqs.forEach(prereqId => {
    result.push(...getPrerequisites(prereqId, depth + 1, visited));
  });
  return result;
}

const fs = require('fs');
const prereqs = {};
ND.forEach(skill => {
  prereqs[skill.id] = getPrerequisites(skill.id);
});
fs.writeFileSync('prereqs.json', JSON.stringify(prereqs, null, 2));
console.log(`Saved prereqs.json — ${Object.keys(prereqs).length} skills`);
