import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Nav
    nav: {
      home: 'Home',
      courses: 'Courses',
      about: 'About',
      login: 'Log In',
      signup: 'Sign Up Free',
      students: 'Students',
      teachers: 'Teachers',
      institutions: 'Institutions',
      searchPlaceholder: 'What do you want to learn?',
    },
    // Landing
    landing: {
      heroTitle: 'Learn Smarter, Not Harder',
      heroSubtitle: 'ATLAS adapts to how you learn — skipping what you already know and focusing on what you need. Powered by AI, personalized for you.',
      heroCta: 'Start Learning for Free',
      heroSecondaryCta: 'See How It Works',
      statsStudents: 'Active Learners',
      statsLessons: 'Lessons Available',
      statsMastery: 'Avg. Mastery Rate',
      featuresTitle: 'Why Students Love ATLAS',
      featuresSubtitle: 'Our platform combines cutting-edge AI with proven learning methods to create a truly personalized education experience.',
      feature1Title: 'Adaptive Learning Engine',
      feature1Desc: 'Our AI tracks what you know using Bayesian Knowledge Tracing and selects the perfect next question — no wasted time on things you\'ve already mastered.',
      feature2Title: 'AI-Powered Grading',
      feature2Desc: 'Write answers in Bangla or English — our system understands partial answers, detects what you know, and explains what\'s missing.',
      feature3Title: 'Smart Hints & Scaffolding',
      feature3Desc: 'Stuck? Get step-by-step hints that break problems into smaller pieces, adjusted to your exact skill level.',
      workflowTitle: 'Your Learning Journey',
      workflowSubtitle: 'Six simple steps to mastery',
      step1: 'Pick a Lesson',
      step1Desc: 'Choose from your course',
      step2: 'Smart Question',
      step2Desc: 'AI picks the right challenge',
      step3: 'Answer It',
      step3Desc: 'Type or select your answer',
      step4: 'Get Feedback',
      step4Desc: 'Instant, detailed explanation',
      step5: 'Level Up',
      step5Desc: 'Your mastery updates live',
      step6: 'Master It',
      step6Desc: 'Reach 95% and move on',
      ctaTitle: 'Ready to Learn Your Way?',
      ctaSubtitle: 'Join thousands of students learning smarter with ATLAS.',
      ctaButton: 'Get Started — It\'s Free',
      footerAbout: 'ATLAS is an AI-powered adaptive tutoring platform that personalizes learning for every student.',
      footerPlatform: 'Platform',
      footerResources: 'Resources',
      footerContact: 'Contact',
      footerRights: '© 2026 ATLAS. All rights reserved.',
      bilingualTitle: 'Learn in Your Language',
      bilingualDesc: 'Full support for both Bangla and English — lessons, questions, grading, and hints all work in your preferred language.',
    },
    // Courses
    courses: {
      welcome: 'Welcome back',
      studentName: 'Student',
      dashboardSubtitle: 'Continue your learning journey',
      activeCourses: 'Active Courses',
      avgMastery: 'Average Mastery',
      weeklyTime: 'Weekly Study Time',
      hours: 'hours',
      searchCourses: 'Search courses...',
      allSubjects: 'All',
      mathematics: 'Mathematics',
      science: 'Science',
      english: 'English',
      physics: 'Physics',
      chemistry: 'Chemistry',
      continueLearning: 'Continue Learning',
      allCourses: 'All Courses',
      lessons: 'lessons',
      mastery: 'Mastery',
      notStarted: 'Not Started',
      startCourse: 'Start Course',
      continueBtn: 'Continue',
      viewCourse: 'View Course',
      noResults: 'No courses found matching your search.',
    },
    // Lessons
    lessons: {
      backToCourses: 'Back to Courses',
      courseProgress: 'Course Progress',
      overallMastery: 'Overall Mastery',
      totalLessons: 'Total Lessons',
      continueLesson: 'Continue Where You Left Off',
      currentLesson: 'Current Lesson',
      continuePractice: 'Continue Practice',
      completed: 'Completed',
      inProgress: 'In Progress',
      available: 'Available',
      locked: 'Locked',
      startLesson: 'Start Lesson',
      resume: 'Resume',
      questions: 'questions',
      mins: 'min',
    },
    // Practice
    practice: {
      question: 'Question',
      of: 'of',
      mastery: 'Mastery',
      submitAnswer: 'Submit Answer',
      yourAnswer: 'Your answer...',
      getHint: 'Get Hint',
      hints: 'Hints',
      hint: 'Hint',
      locked: 'Locked',
      scaffoldingPrompt: 'Your answer...',
      submitStep: 'Check',
      correct: 'Correct! Great job! 🎉',
      incorrect: 'Not quite right. Try again!',
      backToLesson: 'Back to Lesson',
      nextQuestion: 'Next Question',
      hintPanel: 'Hint Panel',
      tryAnswering: 'Try answering first, then unlock hints if you need help!',
      bktDiagnosis: 'Skill Gap Detected',
      bktSubLesson: 'Mini-Lesson',
      bktRetry: 'Retry',
      bktDiagnosisTitle: 'BKT Analysis: Knowledge Gap Found',
      bktDiagnosisDesc: 'Based on your responses, ATLAS identified a prerequisite skill that needs strengthening.',
      prerequisiteSkill: 'Prerequisite Skill',
      wrongAttempts: 'Wrong',
      startSubLesson: 'Start Mini-Lesson',
      skipToRetry: 'Skip & Retry',
      subLessonDesc: 'Practice these prerequisite questions before retrying.',
      practiceQuestion: 'Practice Question',
      nextPractice: 'Next Practice Question',
      finishSubLesson: 'Finish Mini-Lesson',
      subLessonDone: 'Mini-Lesson Complete!',
      subLessonDoneDesc: "You've strengthened the prerequisite skill. Now let's retry the original question.",
      retryQuestion: 'Retry Original Question',
      retryBanner: 'Great! Now try the question again with your strengthened understanding.',
      finishLesson: 'Finish Lesson',
      lessonComplete: 'Lesson Complete!',
      greatJob: "Great job! You've completed all questions.",
      finalMastery: 'Final Mastery',
      bktTrace: 'BKT Trace',
      bktNoEvents: 'Answer questions to see BKT updates',
    },
  },
  bn: {
    nav: {
      home: 'হোম',
      courses: 'কোর্সসমূহ',
      about: 'আমাদের সম্পর্কে',
      login: 'লগ ইন',
      signup: 'বিনামূল্যে সাইন আপ',
      students: 'শিক্ষার্থী',
      teachers: 'শিক্ষক',
      institutions: 'প্রতিষ্ঠান',
      searchPlaceholder: 'আপনি কী শিখতে চান?',
    },
    landing: {
      heroTitle: 'স্মার্টভাবে শিখুন, কঠিনভাবে নয়',
      heroSubtitle: 'ATLAS আপনার শেখার ধরণের সাথে মানিয়ে চলে — যা আপনি জানেন তা এড়িয়ে যায় এবং যা প্রয়োজন তাতে মনোযোগ দেয়। AI দ্বারা চালিত, আপনার জন্য ব্যক্তিগতকৃত।',
      heroCta: 'বিনামূল্যে শেখা শুরু করুন',
      heroSecondaryCta: 'কিভাবে কাজ করে দেখুন',
      statsStudents: 'সক্রিয় শিক্ষার্থী',
      statsLessons: 'পাঠ উপলব্ধ',
      statsMastery: 'গড় দক্ষতার হার',
      featuresTitle: 'শিক্ষার্থীরা কেন ATLAS পছন্দ করে',
      featuresSubtitle: 'আমাদের প্ল্যাটফর্ম অত্যাধুনিক AI এবং প্রমাণিত শিক্ষা পদ্ধতির সমন্বয়ে সত্যিকারের ব্যক্তিগত শিক্ষা অভিজ্ঞতা তৈরি করে।',
      feature1Title: 'অভিযোজিত শিক্ষা ইঞ্জিন',
      feature1Desc: 'আমাদের AI বেইসিয়ান নলেজ ট্রেসিং ব্যবহার করে আপনি কী জানেন তা ট্র্যাক করে এবং নিখুঁত পরবর্তী প্রশ্ন নির্বাচন করে — ইতিমধ্যে আয়ত্ত করা বিষয়ে সময় নষ্ট হয় না।',
      feature2Title: 'AI-চালিত গ্রেডিং',
      feature2Desc: 'বাংলা বা ইংরেজিতে উত্তর লিখুন — আমাদের সিস্টেম আংশিক উত্তর বোঝে, আপনি কী জানেন তা শনাক্ত করে এবং কী অনুপস্থিত তা ব্যাখ্যা করে।',
      feature3Title: 'স্মার্ট ইঙ্গিত এবং ধাপায়ন',
      feature3Desc: 'আটকে গেছেন? ধাপে ধাপে ইঙ্গিত পান যা সমস্যাগুলিকে ছোট ছোট টুকরোতে ভাঙে, আপনার দক্ষতার স্তর অনুযায়ী সামঞ্জস্য করা।',
      workflowTitle: 'আপনার শিক্ষা যাত্রা',
      workflowSubtitle: 'দক্ষতার জন্য ছয়টি সহজ পদক্ষেপ',
      step1: 'পাঠ বাছুন',
      step1Desc: 'আপনার কোর্স থেকে বেছে নিন',
      step2: 'স্মার্ট প্রশ্ন',
      step2Desc: 'AI সঠিক চ্যালেঞ্জ বাছাই করে',
      step3: 'উত্তর দিন',
      step3Desc: 'আপনার উত্তর টাইপ বা নির্বাচন করুন',
      step4: 'ফিডব্যাক পান',
      step4Desc: 'তাৎক্ষণিক, বিস্তারিত ব্যাখ্যা',
      step5: 'লেভেল আপ',
      step5Desc: 'আপনার দক্ষতা লাইভ আপডেট হয়',
      step6: 'আয়ত্ত করুন',
      step6Desc: '৯৫% অর্জন করুন এবং এগিয়ে যান',
      ctaTitle: 'আপনার মতো করে শিখতে প্রস্তুত?',
      ctaSubtitle: 'ATLAS-এর সাথে স্মার্টভাবে শেখা হাজার হাজার শিক্ষার্থীর সাথে যোগ দিন।',
      ctaButton: 'শুরু করুন — বিনামূল্যে',
      footerAbout: 'ATLAS একটি AI-চালিত অভিযোজিত টিউটরিং প্ল্যাটফর্ম যা প্রতিটি শিক্ষার্থীর জন্য শিক্ষাকে ব্যক্তিগতকৃত করে।',
      footerPlatform: 'প্ল্যাটফর্ম',
      footerResources: 'রিসোর্স',
      footerContact: 'যোগাযোগ',
      footerRights: '© ২০২৬ ATLAS। সকল স্বত্ব সংরক্ষিত।',
      bilingualTitle: 'আপনার ভাষায় শিখুন',
      bilingualDesc: 'বাংলা এবং ইংরেজি উভয়ের জন্য সম্পূর্ণ সমর্থন — পাঠ, প্রশ্ন, গ্রেডিং এবং ইঙ্গিত সবকিছু আপনার পছন্দের ভাষায় কাজ করে।',
    },
    courses: {
      welcome: 'স্বাগতম',
      studentName: 'শিক্ষার্থী',
      dashboardSubtitle: 'আপনার শিক্ষা যাত্রা চালিয়ে যান',
      activeCourses: 'সক্রিয় কোর্স',
      avgMastery: 'গড় দক্ষতা',
      weeklyTime: 'সাপ্তাহিক পড়ার সময়',
      hours: 'ঘণ্টা',
      searchCourses: 'কোর্স খুঁজুন...',
      allSubjects: 'সব',
      mathematics: 'গণিত',
      science: 'বিজ্ঞান',
      english: 'ইংরেজি',
      physics: 'পদার্থবিজ্ঞান',
      chemistry: 'রসায়ন',
      continueLearning: 'শেখা চালিয়ে যান',
      allCourses: 'সকল কোর্স',
      lessons: 'পাঠ',
      mastery: 'দক্ষতা',
      notStarted: 'শুরু হয়নি',
      startCourse: 'কোর্স শুরু করুন',
      continueBtn: 'চালিয়ে যান',
      viewCourse: 'কোর্স দেখুন',
      noResults: 'আপনার অনুসন্ধানের সাথে মিলে এমন কোনো কোর্স পাওয়া যায়নি।',
    },
    lessons: {
      backToCourses: 'কোর্সে ফিরে যান',
      courseProgress: 'কোর্স অগ্রগতি',
      overallMastery: 'সামগ্রিক দক্ষতা',
      totalLessons: 'মোট পাঠ',
      continueLesson: 'আপনি যেখানে ছেড়েছিলেন সেখান থেকে চালিয়ে যান',
      currentLesson: 'বর্তমান পাঠ',
      continuePractice: 'অনুশীলন চালিয়ে যান',
      completed: 'সম্পন্ন',
      inProgress: 'চলমান',
      available: 'উপলব্ধ',
      locked: 'তালাবদ্ধ',
      startLesson: 'পাঠ শুরু করুন',
      resume: 'পুনরায় শুরু',
      questions: 'প্রশ্ন',
      mins: 'মিনিট',
    },
    practice: {
      question: 'প্রশ্ন',
      of: 'এর মধ্যে',
      mastery: 'দক্ষতা',
      submitAnswer: 'উত্তর জমা দিন',
      yourAnswer: 'আপনার উত্তর...',
      getHint: 'ইঙ্গিত নিন',
      hints: 'ইঙ্গিত',
      hint: 'ইঙ্গিত',
      locked: 'তালাবদ্ধ',
      scaffoldingPrompt: 'আপনার উত্তর...',
      submitStep: 'যাচাই করুন',
      correct: 'সঠিক! চমৎকার! 🎉',
      incorrect: 'সঠিক নয়। আবার চেষ্টা করুন!',
      backToLesson: 'পাঠে ফিরে যান',
      nextQuestion: 'পরবর্তী প্রশ্ন',
      hintPanel: 'ইঙ্গিত প্যানেল',
      tryAnswering: 'প্রথমে উত্তর দেওয়ার চেষ্টা করুন, তারপর প্রয়োজন হলে ইঙ্গিত আনলক করুন!',
      bktDiagnosis: 'দক্ষতার ফাঁক সনাক্ত হয়েছে',
      bktSubLesson: 'মিনি-পাঠ',
      bktRetry: 'পুনরায় চেষ্টা',
      bktDiagnosisTitle: 'BKT বিশ্লেষণ: জ্ঞানের ফাঁক পাওয়া গেছে',
      bktDiagnosisDesc: 'আপনার উত্তরের উপর ভিত্তি করে, ATLAS একটি পূর্বশর্ত দক্ষতা চিহ্নিত করেছে যা শক্তিশালী করতে হবে।',
      prerequisiteSkill: 'পূর্বশর্ত দক্ষতা',
      wrongAttempts: 'ভুল',
      startSubLesson: 'মিনি-পাঠ শুরু করুন',
      skipToRetry: 'এড়িয়ে যান ও পুনরায় চেষ্টা',
      subLessonDesc: 'পুনরায় চেষ্টা করার আগে এই পূর্বশর্ত প্রশ্নগুলি অনুশীলন করুন।',
      practiceQuestion: 'অনুশীলন প্রশ্ন',
      nextPractice: 'পরবর্তী অনুশীলন প্রশ্ন',
      finishSubLesson: 'মিনি-পাঠ শেষ করুন',
      subLessonDone: 'মিনি-পাঠ সম্পন্ন!',
      subLessonDoneDesc: 'আপনি পূর্বশর্ত দক্ষতা শক্তিশালী করেছেন। এখন মূল প্রশ্নে পুনরায় চেষ্টা করুন।',
      retryQuestion: 'মূল প্রশ্নে পুনরায় চেষ্টা',
      retryBanner: 'দারুণ! এখন আপনার শক্তিশালী বোঝাপড়া দিয়ে আবার প্রশ্নটি চেষ্টা করুন।',
      finishLesson: 'পাঠ শেষ করুন',
      lessonComplete: 'পাঠ সম্পন্ন!',
      greatJob: 'চমৎকার! আপনি সব প্রশ্ন সম্পন্ন করেছেন।',
      finalMastery: 'চূড়ান্ত দক্ষতা',
      bktTrace: 'BKT ট্রেস',
      bktNoEvents: 'BKT আপডেট দেখতে প্রশ্নের উত্তর দিন',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('atlas-lang');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('atlas-lang', lang);
    document.documentElement.lang = lang === 'bn' ? 'bn' : 'en';
  }, [lang]);

  const t = (path) => {
    const keys = path.split('.');
    let value = translations[lang];
    for (const key of keys) {
      value = value?.[key];
    }
    return value || path;
  };

  const toggleLang = () => setLang(prev => prev === 'en' ? 'bn' : 'en');

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
